### ISSUE TITLE
French (Nostalgeek) Client

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#100]
New issues :D 

Some spells are avoid
Exemple : "Enflammer" (https://www.nostalgeek-serveur.com/db/?spell=12654)

Another problem is the segments
-> Segments do not register at the right time, and then I lose the data

**Comment by Geigerkind** [comment]
What do you mean with the segments?

**Comment by Geigerkind** [comment]
Also did you cast the spell or someone else in your group/enemy/npc?

**Comment by Kalandras** [comment]
It was someone else for the cast
And the segments are lost after a moment, I just have my own data and it's not good data. Also they are not registered in the good time. For exemple, the data for the boss "Patchwerk" used the data of the pack after him :x

**Comment by Geigerkind** [comment]
Sorry, I don't understand

**Comment by Geigerkind** [comment]
Well first one is solved, second one you gotta open a new ticket and be a little more detailed and understandable for me ;)
