### ISSUE TITLE
EN Client LUA Error

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#101]
https://img.kalandras.eu/Hq72bs.png

**Comment by Baraz** [comment]
I encountered this error as well, after a total wipe of all things DPSMate and reinstall. Disabling the syncing gets rid of the error but is obviously not a permanent solution.

**Comment by Kalandras** [comment]
Error: Interface\AddOns\DPSMate\DPSMate_Sync.lua:146: attempt to index field `?' (a string value)
--------------------------------------------------

**Comment by Geigerkind** [comment]
Forgot to update the version on LL
