### ISSUE TITLE
Bug French client (Nostalgeek)

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#104]
Hey !
Thx for the great job, this last version look very good !
But a problem appear :x 
When you leave the raid, all the data of the other people except yourself disapear !
https://img.kalandras.eu/yK5ojZ.png
https://img.kalandras.eu/8XRpkW.png
etc..

**Comment by Geigerkind** [comment]
Disable group only :'D

**Comment by Kalandras** [comment]
Ho so it's just an option ? ><
