### ISSUE TITLE
Featured : New graphical column

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#105]
Hey !
Is it possible to have a new graphical option ?
Choose the number of displayed column.

Ex : 
atm we have this display
https://img.kalandras.eu/E7cBza.png

The idea is to have something like this 
https://img.kalandras.eu/yeNS4t.png
but instead of having 8 entries, have 20 :D 

If you understand me <3

PS
And please add me here :o :D <3
https://img.kalandras.eu/L4NzBU.png

**Comment by Geigerkind** [comment]
I don't understand your request^^

**Comment by Kalandras** [comment]
How to explain that ><
At the moment we only have one big column displayed
I want the possiblity to choose to display 2/3 or 4 column :)

**Comment by Geigerkind** [comment]
Oh, ehm no, not going to implement this, sorry.
I decided against this from the very beginning.

**Comment by Kalandras** [comment]
:(
