### ISSUE TITLE
Conflict with MikeScrollingBattleText

### ISSUE THREAD

**Issue by chenningfugg** [Geigerkind/DPSMate#109]
When I Add lines codes to my WTF/config.wtf , everytime I reload my addons or close my client , the config.wtf will be changed, and which codes I had added disppeared. Anyone can deal with ?

**Comment by Geigerkind** [comment]
You mean the values for the combat log range?

Not sure what MSBT does there. Try to adjust the max value to 150

**Comment by chenningfugg** [comment]
Actually,the addon which named of MikeScrollingBattleText will change my config.wtf. I mean that could u find any way to change the combat log range instead of adding lines to config.wtf ? I appreciate.

**Comment by Geigerkind** [comment]
Ya, prob, will look into the addon code.
