### ISSUE TITLE
Don't show line with my dmg :(

### ISSUE THREAD

**Issue by babooin** [Geigerkind/DPSMate#110]
DPSmate at the first start it works fine, after a while it stops showing my damage at all! I tried everything, right up to reinstalling and reconfiguring the game client is complete. Help me pls, what wrong with my addon?((

<a href="https://imgdepo.com/show/10642791" target="_blank"><img src="http://imgdepo.com/thumb/2017/May/15/79d0c19a.jpg"/></a>

**Comment by Geigerkind** [comment]
Is your client in the russian language?

I didnt write the parser for this language so maybe there is a bug with that.

cheers!

**Comment by babooin** [comment]
Nah, client is true english. I just belong to the Russian guild, if you talk about chat in russian lng.

**Comment by Geigerkind** [comment]
Hmm, check your filter settings.
Also did you load the release version or master branch?

**Comment by babooin** [comment]
My filter settings is ok, all classes enabled. Yes, I did download the master branch. Will try release.

**Comment by babooin** [comment]
I put the release version 114 clean, the problem did not disappear :(

**Comment by Geigerkind** [comment]
Ah okay!
Lets see what I can do with that, thy!

**Comment by Geigerkind** [comment]
Okay should work now when you load the master branch and reset once total
