### ISSUE TITLE
Problem with the Launcher

### ISSUE THREAD

**Issue by m00s3m4n** [Geigerkind/DPSMate#112]
When using the new version of the Launcher, it keeps saying the WTF fold is read only, even though it isn't. Subsequently, there won't be any logs uploaded

**Comment by fidbugs** [comment]
Having the same issue as of recent Launcher update, using Windows 10 - which apparently has every folder flagged by default as read only . Tried everything to remove it but cant, thus keep getting same error message and can not upload logs.

**Comment by Geigerkind** [comment]
Forgot to comment something out, sorry :S
