### ISSUE TITLE
Invalid user passed into GetClassColor()

### ISSUE THREAD

**Issue by Road-block** [Geigerkind/DPSMate#113]
This is about [ef97669](https://github.com/Geigerkind/DPSMate/commit/ef9766989a778293b4833e323a366703098cc7dd).  
In some circumstance that I didn't debug GetClassColor() [DPSMate.lua#L564](https://github.com/Geigerkind/DPSMate/blob/master/DPSMate/DPSMate.lua#L564) gets passed `LASTRESETDPSMATE` instead of a unit name.  
This causes it to error ad infinitum until the user does a reset.  
It passes the conditional and tries to get r,g,b for `DPSMateUser[LASTRESETDPSMATE][2]` which contains the build number (116 in my case).  
I didn't try to trace the caller but maybe [DPSMate.lua#L451](https://github.com/Geigerkind/DPSMate/blob/master/DPSMate/DPSMate.lua#L451)?

**Comment by Road-block** [comment]
On an unrelated note.  
On first launch with the new version (from a cold login) I got an error on [DPSMate_Options.lua#L761](https://github.com/Geigerkind/DPSMate/blob/master/DPSMate/DPSMate_Options.lua#L761) with a message of CVar 'CombatLogRangeParty' doesn't exist.
A /console reloadui seems to have cleared it up.   
Could it be a loading order issue?

**Comment by Road-block** [comment]
I went back to 2ae1f98128aca3cb9cad2460037d6acb04b9ee5f for now, it's error free.

**Comment by Geigerkind** [comment]
Yep, Prob a loading order issue.

**Comment by Geigerkind** [comment]
Should be fixed now. Will test it when I am at home

**Comment by Road-block** [comment]
Did you also look at the first error?  
The cvar was a minor annoyance it only happened once, the GetClassColor() error is the one that spams constantly.

**Comment by Geigerkind** [comment]
Yep, Should Not cause an Issue anymore
