### ISSUE TITLE
Problem with overheal

### ISSUE THREAD

**Issue by lurexx** [Geigerkind/DPSMate#114]
Overhealing is not being recorded correctly, or atleast not all of it.

I suspect the issue is the modules enabled, since it works when all modules are enabled.
http://imgur.com/a/p0U8s

**Comment by lurexx** [comment]
Also, this log seems to be bugged too:^
https://legacy-logs.com/Vanilla/Raids/Evaluation/Healing/index.php?rid=11578&attempts=&player=&sel=0&pet=0&tarid=&mode=0

The OH is far too low once again.
Vnm has 10%, and he should have between 33-35% for instance ( we checked this with his ingame logs)

**Comment by Geigerkind** [comment]
Any hints which modules could be meant^^?

**Comment by Geigerkind** [comment]
Also please tell me which modules are enabled in your config.

**Comment by lurexx** [comment]
The imgur link specifies that

**Comment by Geigerkind** [comment]
thank you! :>

**Comment by lurexx** [comment]
Okay, tried the new build
And I confirmed that it works when all modules are enabled, however it still bugs on OH when the above modules are disabled.

**Comment by Geigerkind** [comment]
Okay, thanks!

**Comment by Geigerkind** [comment]
Can you tell me what parts are not tracked?
Dots, or overall a little, some screens as references ?

**Comment by lurexx** [comment]
DPSMate: enabled
DPSMate_Threat: enabled
DPSMate_!zhCN: disabled
DPSMate_!ruRU: disabled
DPSMate_!frFR: disabled
DPSMate_!deDE: disabled
DPSMate_LiftMagic: enabled
DPSMate_LiftMagicReceived: enabled
DPSMate_Interrupts: enabled
DPSMate_HealingAndAbsorbs: enabled
DPSMate_FriendlyFire: enabled
DPSMate_FriendlyFireTaken: disabled
DPSMate_Fails: disabled
DPSMate_EDT: enabled
DPSMate_EDD: enabled
DPSMate_DecursesReceived: disabled
DPSMate_AbsorbsTaken: disabled
DPSMate_Absorbs: enabled
DPSMate_Activity: enabled
DPSMate_Auras: enabled
DPSMate_CCBreaker: disabled
DPSMate_Casts: enabled
DPSMate_CureDiseaseReceived: disabled
DPSMate_CureDisease: disabled
DPSMate_CurePoisonReceived: disabled
DPSMate_CurePoison: disabled
DPSMate_Decurses: disabled
DPSMate_DispelsReceived: disabled
DPSMate_Dispels: enabled

**Comment by lurexx** [comment]
Edit, comparison of what is enabled can be seen in the document below for easy viewing.
https://docs.google.com/spreadsheets/d/1q4Mr-M4ORbrP9QB45aniWA9MX2rsuOwB3nu0rgda9Y4/edit?usp=sharing

Note, some  weeks ago, i tried to enabled modules on my paladin to match my priest, i just forgot about it.
The overhealing still bugged tho, and i can see that i failed to match the modules enabled too, but that might make it easier to pinpoint the problem, cheers.

**Comment by Geigerkind** [comment]
I reworked it in the non legacy logs version of the addon.
