### ISSUE TITLE
function DPSMate:GetClassColor(class) ERROR

### ISSUE THREAD

**Issue by Zoups** [Geigerkind/DPSMate#116]
When in Raid I sometimes get an error (Sync disabled) :

![image](https://cloud.githubusercontent.com/assets/28675988/26413034/fdc60382-40aa-11e7-847e-2f024bb2b923.png)

```lua
564  function DPSMate:GetClassColor(class)
565  	if class and not classcolor[class] then
566  		class = DPSMateUser[class][2] or "warrior"
567  	else
568  		class = "warrior"
569  	end
570  	return classcolor[class].r, classcolor[class].g, classcolor[class].b, class
571   end
```

**Comment by Zoups** [comment]
Any comment on the Issue ?

**Comment by Geigerkind** [comment]
Sorry, its solved in the Master, will be fixes in the next Build
