### ISSUE TITLE
There is no record statistics of the player who writes the logs.

### ISSUE THREAD

**Issue by 0ldi** [Geigerkind/DPSMate#117]
I have not my combat logs, but other raid-members have (this is not only my problem, all with last week version have this bug).
And this buged logs upload on LL
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=11786

**Comment by RussianE39** [comment]
I have strong suspicion, that problem arise after this commit:

https://github.com/Geigerkind/DPSMate/commit/c16edfccd3285f04a11927e8136002029771f461

**Comment by Geigerkind** [comment]
Nope that one is it definitely not. I have also an suspicion which I will investigate this night.

**Comment by Geigerkind** [comment]
Please report if it is fixed in the next version!

**Comment by Tegas** [comment]
Just ran a raid with the latest release (it was 15 minutes fresh when I downloaded it) and my toon didn't show up in the logs on the site. I did show up in the in game version.

https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=11611
Char is Tegan (hence the uploaded by, but I don't show up in any of the stats (i was healing)).

**Comment by Geigerkind** [comment]
Ok, I found the root of the problem now. Need to figure out now how it is caused.

**Comment by Geigerkind** [comment]
Fixed
