### ISSUE TITLE
DPSMate.lua nil value

### ISSUE THREAD

**Issue by Baraz** [Geigerkind/DPSMate#118]
![error](https://cloud.githubusercontent.com/assets/16702112/26547590/045fc3fe-4470-11e7-84c6-65ce47c78968.png)
![error2](https://cloud.githubusercontent.com/assets/16702112/26547598/0c0dd1ea-4470-11e7-938b-e1630425288e.png)

**Comment by Geigerkind** [comment]
Fixed in the next build. Will push an update this evening.
