### ISSUE TITLE
Unable to upload logs

### ISSUE THREAD

**Issue by fidbugs** [Geigerkind/DPSMate#119]
For few weeks i have issues with uploading. First i could not use launcher(WTF folder seen as read only), but now everything seems OK, launcher starts normal, raid is recorded but when i exit game it just goes quickly to "Uploading..." than "Upload complete" after second. Nothing gets uploaded.

I tried running as administrator, adding firewall exception, but nothing helps.

Would like to continue to use this amazing addon, but if i cant upload raids than it is of few use to me. 

BTW using Windows 10, updated to latest version.

**Comment by Geigerkind** [comment]
Hey!
Try using the java version of the launcher for now. There seems to be a little issue with the normal one.
I try to resolve the issue soonish.

cheers!

**Comment by Geigerkind** [comment]
Fixed it!
