### ISSUE TITLE
DPSMate b121 dont auto write CombatLogRange into Config.wtf ?

### ISSUE THREAD

**Issue by Timolol2012** [Geigerkind/DPSMate#121]
i cant find these code in Config.wtf  after exit game

SET CombatLogRangeParty  "200"
SET CombatLogRangePartyPet "200"
SET CombatLogRangeFriendlyPlayers "200"
SET CombatLogRangeFriendlyPlayersPets "200"
SET CombatLogRangeHostilePlayers "200"
SET CombatLogRangeHostilePlayersPets "200"
SET CombatLogRangeCreature "200"
SET CombatDeathLogRange "200"

**Comment by Geigerkind** [comment]
I dont know why it is never saved, but it will be set everytime you log in :)
