### ISSUE TITLE
something wrong with ClassColor

### ISSUE THREAD

**Issue by Timolol2012** [Geigerkind/DPSMate#122]
![default](https://user-images.githubusercontent.com/26404230/26979534-b8b00b26-4d61-11e7-8f02-b796b94e75c2.png)

**Comment by Timolol2012** [comment]
DPSMate b121

**Comment by Geigerkind** [comment]
Are you sure that you have already got to know these character classes by forming a group with them or targeting them?

**Comment by Timolol2012** [comment]
Timolol is me, iv  killed some mobs for test, logout then login game ,my clour still like this

**Comment by Timolol2012** [comment]
im a rogue

**Comment by Timolol2012** [comment]
test it again, logout & login game, ClassColor working properly

**Comment by Geigerkind** [comment]
aight :)
