### ISSUE TITLE
contentbordercolor a nil value

### ISSUE THREAD

**Issue by nydokade** [Geigerkind/DPSMate#123]
Error: Interface/addons/DPSMate/DPSMate.lua:202: attempt to index field "contenbordercolor" a nil value

every modul is in AddOn folder, old dpsmate.lua/bak in config is deleted + config

i dont get any data from the addon, i just see the yellow window with nothing in it
tried everything to fix, i dont get it :/

**Comment by Geigerkind** [comment]
Did you delete the DPSMate.lua/bak in your account savedvariables as well?

**Comment by nydokade** [comment]
yep!

**Comment by Geigerkind** [comment]
Sorry for this asking, but this error usually only appears if the DPSMate.lua/bak has not been resetted properly.
http://i.imgur.com/P0fbdpT.png

So I really want to make sure that you quit the game, deleted all DPSMate.lua/bak files and then started it again.

**Comment by nydokade** [comment]
ok got a fix/ maybe i did it wrong,

i searched into the WTF folders for DPSMate and deleted everything, after this i replaced the dpsmate (not first deleted it and then paste it) maybe this helped, idk...

sorry for taking ur time away, but lets hope this thread helps another soul then ;/

**Comment by Geigerkind** [comment]
Dont worry^^
no problem!
