### ISSUE TITLE
How to track people getting hit by specific boss ability ?

### ISSUE THREAD

**Issue by Zoups** [Geigerkind/DPSMate#125]
Hello, I'm trying to track all the people who get hit by a particular Boss ability.

In "Damage Taken" I can only check damage taken from 1 player. So I need to check them 1 by 1 ... kind of long process.
I tryed to use "Ennemy damage done", but it's also sorting every raid member.

Any faster way ?

**Comment by Geigerkind** [comment]
Enemy damage done, prob.
