### ISSUE TITLE
something wrong with ClassColor

### ISSUE THREAD

**Issue by hellmoon** [Geigerkind/DPSMate#127]
![image](https://user-images.githubusercontent.com/29900112/27840703-d05bb7f6-6103-11e7-9c79-8a7c14e8d5c3.png)

**Comment by niklasbe** [comment]
Me too. Shows me as Warrior (I'm Warlock) and it doesn't list my pet

**Comment by Geigerkind** [comment]
Usually targeting yourself fixes the issue.
