### ISSUE TITLE
604hours combat time.

### ISSUE THREAD

**Issue by RussianE39** [Geigerkind/DPSMate#131]
Sometimes recording could be ruined by 604hours combat time. Especially if some person uses slightly older DPSMate version. More interesting, that in game I had different results comparing to web site ones.
http://mepic.ru/up/pic_b/5205b96619a335e4d5a27f14ae285660.jpg

Example:
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=14808

**Comment by Geigerkind** [comment]
Its 10H combat time, but its still wrong.
Any clues how it can be caused? Cause DPSMate should not sync with older versions normally.

**Comment by coryo** [comment]
I've had the same problem happening where I get huge amounts of combat time added.

http://www.legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=14738
https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=14867

from my dpsmate from BWL it seems like the time got added around chromaggus. I did log off around then to save some buffs before the last boss.
![image](https://user-images.githubusercontent.com/678207/28726508-80d86e92-738f-11e7-847c-b20d07125421.png)

**Comment by RussianE39** [comment]
We had 5 ppl with DPSMate in raid, 4 of them used v124, and one person used v120. I'm suggesting version check on sync channel join and not syncing with DPSMate version which is lower than you using.

**Comment by RussianE39** [comment]
Seems older DPSMate versions is not an issue, as we experienced same behaviour when 11ppl used 124 version.

**Comment by Geigerkind** [comment]
Added a counter measure
