### ISSUE TITLE
Threat doesn’t show up

### ISSUE THREAD

**Issue by ghost** [Geigerkind/DPSMate#132]
I’m not sure if it’s just me, but I can’t get threat to show up. I have DPSMate, DPSMate_Threat, and KLHTHreatMetter installed. As can be seen on the screenshot KTM works, but DPSMate_Threat doesn’t. Do I need to install another module or do something else?

![wowscrnshot_072917_124554](https://user-images.githubusercontent.com/30494689/28743833-7220fa5e-745c-11e7-8578-5561888b4315.jpg)

**Comment by Geigerkind** [comment]
Could you upload your KTM version for me?

**Comment by kyresong** [comment]
Doesn’t work for me either. I’ve tried the 17.23 and Mesmerize edition form here: http://addons.us.to/addon/klhthreatmeter-0
