### ISSUE TITLE
Dpsmate not showing % of hits getting glancing

### ISSUE THREAD

**Issue by jockeboschko** [Geigerkind/DPSMate#133]
As stated in the title dpsmate does not show glancings and instead throws it together with regular hits. 

https://gyazo.com/e09760731dd9142e0ad82908fe2c87bc

Also armory addon doesnt seem to be working when u log on elysium as seen here: https://legacy-logs.com/Vanilla/Raids/Evaluation/index.php?rid=16486

the addon is the latest version installed and shows up in addon list ingame

**Comment by Razorwynd** [comment]
The thing is, I have seen screen caps of the addon where glancing blows are shown, but i do not know how that was accomplished. I think we must be doing something wrong

**Comment by jockeboschko** [comment]
maybe they have an older version and something have been broken in a newer update

**Comment by Geigerkind** [comment]
Will test it right now !

**Comment by Geigerkind** [comment]
Could reproduce it, attempt fixing it now.

**Comment by Geigerkind** [comment]
Does this also happen with everyone else?

**Comment by Geigerkind** [comment]
Apparently. Fixed

**Comment by Razorwynd** [comment]
NICE i will test tonight after work! Thanks so much!

**Comment by Razorwynd** [comment]
So it looks like DPS values that show up are now broken after this update as in the numerical value does not agree with what my DPS should be
