### ISSUE TITLE
Launcher stopped working

### ISSUE THREAD

**Issue by Gorgorel** [Geigerkind/DPSMate#135]
Hi again Geigerkind,

thanks for that awesome tool. I'm using DPSmate since October and uploaded a bunch of raids from November till January. I stopped doing so cause LLLauncher.exe wouldn't start anymore, thus no uploads. Still using DPSMate though w/o any problems. 

Error msg I get when opening LLLauncher (w/ and w/o adminrights):
http://i.imgur.com/hWTQ29R.jpg Imgur link to the error message.
This is german as you might know, saying that LLL isn't working anymore. 

What I did:
+ removed every legacylog & dpsmate .lua and .bak on my system.
+ downloaded the newst version of DPSMate and LLLauncher.
+ set exceptions in the firewall

Any idea what else it could be?
Using the english WoW client with Win 7 pro and had no probs uploading as mentioned. Not sure what changed back then.

Help greatly appreciated.
Cheers!
Mailed this to Geigerkind, posted and PMed on vanillagaming forums so this is somehow my last chance to get helpful input.

**Comment by Geigerkind** [comment]
Hey!
Here are a few things you could try:
1. Try using the Java or Not Java version.
2. Try to remove readonly properties from your world of warcraft folder

cheers!

**Comment by Gorgorel** [comment]
Thank you for the fast reply Geigerkind!

I  tested all 3 clients several times, at different times throughout versions. The non Java version doesn't work anymore (screenshot above), the two Java versions can't find the WoW.exe anymore. I tried moving the whole install and relocate etc.
I don't know what happened in January that causes these issues.

**Comment by Geigerkind** [comment]
Okay.
Thats unfortunate.
Luckily the new version of the website is soon in alpha.
You can view the progress here https://discord.gg/JMQrrqy

For now I will close this issue, cause it will be fixed with the new iteration
