### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by konbizz** [Geigerkind/DPSMate#136]
It seems that the block isn't calculated correctly. 

It looks like that the addon only search the combat log for the text "blocked" and adds a +1 each time it finds something blocked instead of writing how much got an attack got blocked. 

Sometimes you could have eg. Attack critically hit x for 30(x got blocked) this will only show up as blocked if you look up the damage.

**Comment by Geigerkind** [comment]
Related to the glancing problem. Fixed
