### ISSUE TITLE
My logs do not show up

### ISSUE THREAD

**Issue by Larirawiel** [Geigerkind/DPSMate#137]
Hi,

i have uploaded two big logs but they did not appear on the legacy-logs website. Here are the logs.
[DPSMate-Save-Larirawiel-27-08-17-22-45-51.lua.gz](https://github.com/Geigerkind/DPSMate/files/1261389/DPSMate-Save-Larirawiel-27-08-17-22-45-51.lua.gz)
[DPSMate-Save-Larirawiel-28-08-17-21-32-01.lua.gz](https://github.com/Geigerkind/DPSMate/files/1261390/DPSMate-Save-Larirawiel-28-08-17-21-32-01.lua.gz)

Thanks in advance

**Comment by Geigerkind** [comment]
Will post an update to legacy logs soon regarding this topic!
