### ISSUE TITLE
Loot doesn't get logged?

### ISSUE THREAD

**Issue by l1amm** [Geigerkind/DPSMate#138]
I've noticed some guilds on LegacyLogs have loot with their logs. DPSMate doesn't seem to save anything for DPSMateLoot. I have legacy logs checked in the config window for DPSMate, but I'm wondering if maybe "DPSMateSettings["legacylogs"]" is nil ?

Anyone able to get loot working with legacylogs that can tell me how ?

Edit: looked in DPSMate.lua log file after raid. DPSMateLoot is empty... "DPSMateLoot = { }"

**Comment by Geigerkind** [comment]
LegacyLogs support will be removed anyway with the comming release of legacyplayers. Will post a thread for this matter soon!
