### ISSUE TITLE
Tooltip improvements

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#14]
http://puu.sh/t91KN/e4503d435e.jpg
DPS mate has the "top 3 abilities" section already
I want the "top 3 attacked"
then you can easily see like uh... is this guy even attacking the fucking eyes on Cthun for instance
DPSmate has this info but you got to go to each player>each spell>change mode

**Comment by jinthaalor** [comment]
This Option would also be great for enemies.
Example:  The exploding scarabs on Twin Emperors, so you can see easily who received the most damage from the explosion. Mouseover in the enemy damage taken-section, then open details, then mouseover the explode-ability, and see how much damage every player took.

**Comment by Geigerkind** [comment]
Will be implemented with the next version
