### ISSUE TITLE
Glancing blows aren't tracked anymore for some reason

### ISSUE THREAD

**Issue by ohganot** [Geigerkind/DPSMate#141]
For some reason, glancing blows aren't tracked for a while now in my DPSmate. It used to work with an old version, but then now that I use the newer versions, it doesn't work.

Glancings still show up in combat log, but dont show up in DPSmate. https://gyazo.com/b4051483b60d78cf1946877048b82ce5

**Comment by Geigerkind** [comment]
Fixed
