### ISSUE TITLE
DPSMate tracks time when it shouldn't

### ISSUE THREAD

**Issue by ohganot** [Geigerkind/DPSMate#145]
I often have problems that DPSMate is active and counting time when its not supposed to.
It usually happens when I have it disabled and enable it before boss encounter. It seems the time keeps running when DPSMate is disabled.

I usually reset it too but doesn't seem to work for the time.

https://gyazo.com/502a29d5baf6a7acdfc0ea5995768013

**Comment by Geigerkind** [comment]
Fixed
