### ISSUE TITLE
Attempting to index a nil value

### ISSUE THREAD

**Issue by Suzaru** [Geigerkind/DPSMate#147]
Hi!

I'm new to DPSMate and I'd love to use it.
But no matter which version I try to install it just gives me errors.
"Line XY: Attempting to index a nil value"

I'm using the enGB Client.

Thanks

**Comment by Road-block** [comment]
Clear your saved variables for DPSMate and reconfigure.  

- Exit the game
- Navigate to `<wow folder>\WTF\` and do a search (F3 or Ctrl+F in file explorer) for `DPSMate*`  
- Delete the found files
- Start the game

**Comment by Suzaru** [comment]
Alright tried this. Is the newest version compatible to WoW 1.2.1?

**Comment by Road-block** [comment]
I hope you mean 1.12.1 :-)  
In any case https://github.com/Geigerkind/DPSMate/releases/latest is compatible with Classic WoW (also known as vanilla)

**Comment by Geigerkind** [comment]
Use Version 125 or 124 for now if this error occours and delete DPSMate.lua and DPSMate.lua.bak if you have errrors then.

**Comment by Suzaru** [comment]
I just reinstalled the whole thing and now its working. Thanks :)

**Comment by Geigerkind** [comment]
Thanks @Road-block for supporting everyone, while im not here!
