### ISSUE TITLE
Unable to change dps mate settings

### ISSUE THREAD

**Issue by Hapsen** [Geigerkind/DPSMate#149]
I have looked around and don't seem to be able to find anyone with this problem and I am out of things to try.

Unable to change any settings in dps mate via using the sliders
Unable to use drop downs
I don't know if there's more when this happens since I have never gotten past the 'set up' phase

I know this is a horrible bug report but I feel I have tried anything things to work around this, installed a completely fresh version of vanilla wow because I thought I'd just set it up and steal the saved variables from there and I had the exact same problems.
https://youtu.be/A8MYFb5ptZI  This is an awful to watch recording of me trying out a fresh install of vanilla with dps mate.

Since I've been unable to find anyone else with this bug I'm thinking maybe its related to my pc?

**Comment by Geigerkind** [comment]
Hmm, cant think of anything.

You said its a fresh install, so all WTF variables should be fine.

Maybe try to disable some modules?
So you only have the default one? Maybe one of the modules causes that.

cheers!

**Comment by Hapsen** [comment]
disabling modules was the fix.
