### ISSUE TITLE
Getting spammed with an error: "attempting to concatenate a nil value"

### ISSUE THREAD

**Issue by GrungeLord** [Geigerkind/DPSMate#15]
http://i.imgur.com/AM93RHj.jpg I'm sure I've just done something really basic and dumb as I don't know anything about coding. 
  
Here's line 93 of my DPSMate_Damage.lua http://i.imgur.com/I88lZsn.png
  
I was hoping I could get some help in fixing this. I'm not sure exactly what I did to cause this, I messed around with DPSMate_Frame.xml to make the main bars a bit further down from the title bar.  
I also changed a few variables around in DPSMate_damage to make the text read more like recount. [damage (dps, percent)]. Not exactly sure what I did there, but I reverted it to the original code when I started getting the error.  
  
I tried replacing my DPSMate with the latest version and I still get the error.  
  
It seems to happen when the addon picks up another player's dps, I don't get it when I'm solo killing a mob.  
  
The actual addon seems to be functioning properly as far as I can tell, I'm just being flooded with errors.

**Comment by Geigerkind** [comment]
Will look into it at the weekend

**Comment by GrungeLord** [comment]
I actually fixed the issue by deleting all DPSMate related files in WTF and then deleting and redownloading the addon. I thought I had already tried that before I made this post but I guess I was wrong.   
  
On an unrelated note, you wouldn't happen to know why bartender's micromenu disappears in ShaguUI when you inspect someone would you? (It's okay if you don't I know it's no longer supported!) :stuck_out_tongue:

**Comment by Geigerkind** [comment]
No, you should report this bug to Shagu I guess^^
