### ISSUE TITLE
Interface error

### ISSUE THREAD

**Issue by gg123xc** [Geigerkind/DPSMate#150]
I get this error when I load a character with DPSMate.
https://puu.sh/xXGs7/10c0b9f95c.png

**Comment by Vitoshka** [comment]
[2017/10/14 20:34:29-1032]: DPSMate\DPSMate_DataBuilder.lua:661: Couldn't find CVar named 'CombatLogRangeParty'
<in C code>: in function `GetCVar'
DPSMate\DPSMate_DataBuilder.lua:661: in function `?'
DPSMate\DPSMate_DataBuilder.lua:2444: in function <Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:2444>

**Comment by Geigerkind** [comment]
Fixed
