### ISSUE TITLE
Meters only show up for party members while still in party

### ISSUE THREAD

**Issue by ScarletVillain** [Geigerkind/DPSMate#151]
This is for version 124. Just noticed it's not quite current so I'll also try the 126 now.

Everyone in my party shows up on my dps meters but when they leave the party, they disappear from the list. This is for previous fights like boss fights, total amounts. If they rejoin the party their numbers show up again, but only while they're partied with me.

So at the end of an instance run, I can see everyone's damage but only until they leave the party, then it's just my numbers showing. If I reinvite them to the party I can see their damage numbers back again. Is that the way it's supposed to work, cause I don't see any options to change it.

When I review saved boss fights, it'll just be my damage, unless I can reinvite those that were in the party when we did the fight, then they all show up again on the list.

**Comment by ScarletVillain** [comment]
No, version 126 is more broken.

**Comment by l1amm** [comment]
Theres an option to only show players in your current group.

**Comment by ScarletVillain** [comment]
Ah yes in Filter Options there was a checkmark beside Group only. You just click it again to uncheck it and it works the way I wanted.

**Comment by Geigerkind** [comment]
Aight. Guess its fixed^^
