### ISSUE TITLE
dpsmate.lua:572

### ISSUE THREAD

**Issue by PureMalice** [Geigerkind/DPSMate#152]
fresh install of latest dpsmate constantly getting this error and its spamming my chat window 

ERROR: interface\addons\dpsmate\dpsmate.lua:572: attempt to indes field `?' (a nil value).

**Comment by Road-block** [comment]
Band-aid fix.  
Go to [this line](https://github.com/Geigerkind/DPSMate/blob/2c7a3d108a7b980b16c36a29bc277fb99943fca0/DPSMate/DPSMate.lua#L564) and replace that function with 
```lua
function DPSMate:GetClassColor(class)
	if not classcolor[class] then
		if class and DPSMateUser[class] then
			class = DPSMateUser[class][2] or "warrior"
		else
			class = "warrior"
		end
	end
	if classcolor[class]==nil then class="warrior" end
	return classcolor[class].r, classcolor[class].g, classcolor[class].b, class
end
```

**Comment by Geigerkind** [comment]
Fixed
