### ISSUE TITLE
DPSMate not showing Threat

### ISSUE THREAD

**Issue by BeerfishWoW** [Geigerkind/DPSMate#155]
Installed and enabled DPSMate and KLHThreatMeter, incl. DPSMate_Threat, but the Threat window of DPSMate isn't showing Threat data. KTM does show the data, though. Is DPSMate_Threat broken?

**Comment by Geigerkind** [comment]
Was a loading issue. Its fixed now

**Comment by So1ene** [comment]
This is happening to me, I even tried disabling the KTM addon. After reloading wow, the DPSMate threat addon doesn't even want to be enabled anymore!
