### ISSUE TITLE
"total" vs "current fight"

### ISSUE THREAD

**Issue by brolernus** [Geigerkind/DPSMate#157]
Not sure if this is intended, unfixable or just an oversight but "current fight" only starts recording once in combat. So as a hunter your initial pull dmg is only shown on "total".

**Comment by brolernus** [comment]
also using feign death resets the "current fight" recording, this wasn't the case in older versions

**Comment by Geigerkind** [comment]
yep, first one is intended, just reset manually then I guess :/
Working on second now

**Comment by Geigerkind** [comment]
Fixed
