### ISSUE TITLE
localization suport?

### ISSUE THREAD

**Issue by gamer4eg** [Geigerkind/DPSMate#16]
Do you plan to support other client input languages?
PS fu*** google translater...

**Comment by Geigerkind** [comment]
You mean french, russion, spanish, mandarin and other? 
Yes, but I don't know any of these languages and need a translator

**Comment by gamer4eg** [comment]
I can help with the Russian language.
Here spell.dbc files (spells) and GlobalStrings.lua (Combat log)
Just ready to test in Russian. I can provide more files for comparison.
Link: https://drive.google.com/open?id=0B2RWjLl8UkfxMld4c05INzV2UXM

**Comment by Geigerkind** [comment]
Uuuh sweet. 
Could you also do the localization, meaning just make a file ruRU in this format:
https://github.com/Geigerkind/DPSMate/blob/master/localization/deDE.lua

You can find the english translations here:
https://github.com/Geigerkind/DPSMate/blob/master/localization/enUS.lua

cheers :>

**Comment by gamer4eg** [comment]
Many lines ... But I will take part of the Recount localization :)
Maybe we should start with the parser? Localized interface is convenient, but not necessary for the job - as opposed to the parser.
PS I will translate. Not right away. Yes, I'm lazy)

**Comment by Geigerkind** [comment]
No problem. Take it whereever you want from as long it matches what it actually should mean^^

Parsing is a difficult process in vanilla, especially since I am using many work arounds.

I don't have time for that currently unfortunatly, because I have to study for an exam for university. 

But I see how I can squeeze in a little work step by step 

cheers!

**Comment by Geigerkind** [comment]
https://github.com/M2us/DPSMate

**Comment by gamer4eg** [comment]
This is one of ruRU client 1.12.1 = developer) wrote to him and realized that will not pull. =)

**Comment by Geigerkind** [comment]
"That will not pull", what do you mean by that?
