### ISSUE TITLE
Pet does not show up as seperate

### ISSUE THREAD

**Issue by ZetoxZ** [Geigerkind/DPSMate#161]
Cannot see pet as a separate identity in damage shown; only shows if 'merge pet' option is checked.

**Comment by onidesu** [comment]
@ZetoxZ It's a bug, but if you have Merge pets unchecked. You need to uncheck Group only in Filter options on the window itself.

As for @Geigerkind he needs to have it show pets under Group only if they have Merge pets unchecked.

**Comment by Geigerkind** [comment]
Fixed!
