### ISSUE TITLE
Bug Anub'Rekhan/Disease on parse

### ISSUE THREAD

**Issue by Pasloindetoi** [Geigerkind/DPSMate#162]
Hey bro, 

Firstly, sorry for my english I'm french.
Secondly, thanks for your job, it's really an amazing tool ! it helps our guild a lot.

We use Dpsmate build 125.

I have two issues :

1) On AnubRekhan in Naaxramas, we saw that the little critter were not count on the website as they were in the in-game addon.
Just look at our mage/warlock DPS who frequently AOE the scarabs during the fight.
https://legacy-logs.com/Vanilla/Raids/Evaluation/DmgTaken/index.php?rid=4139&attempts=440543,440545,440547,440572,440579&player=&sel=440543&pet=0&tarid=&mode=1

2) On Dpsmate/LegacyLogs, we cannot see the correct dispell count (be it curse, poison or disease).
We only see our own character dispell which still looks buggy.

For exemple, on our Heigan fight, there is a lot of dispell but none of them are visible on the stat page.

https://legacy-logs.com/Vanilla/Raids/Evaluation/Dispels/index.php?rid=4139&attempts=440543,440545,440547,440572,440579&player=&sel=440572&pet=0&tarid=&mode=0

Thx a lot in advance

**Comment by l1amm** [comment]
Issue should be closed, legacy-logs is no longer relevant.
