### ISSUE TITLE
Periodic Freezing with DPSMate

### ISSUE THREAD

**Issue by KevinTyrrell** [Geigerkind/DPSMate#163]
I followed the guide to extend the range of the combat log and now every 30 seconds or so it my wow client will freeze for about 2 seconds. I am not 100% sure if the freezes happened on a normal install or not but I don't think so. 

I tried running DPS Mate with ONLY the base addon (none of the other modules) and the freezing still occurs. 

Any ideas for a way to remedy this, or why it could be happening?

**Comment by KasVital** [comment]
same problem

**Comment by jesterlol** [comment]
so no answer on this problem? Freezes keep happening for almost anyone I know on Elysium, so everyone switched to sw_stats.

**Comment by jesterlol** [comment]
hello?

**Comment by jesterlol** [comment]
so I assume this addon is no longer supported?

**Comment by Zoups** [comment]
This Addon is functional and supported, Geigerkind is busy on another project atm.

1/ Did you try with the latest version of DpsMate ?
2/ Does the freeze also happend when only Dpsmate is enable (other addons disabled)
3/ Try to manually reset DpsMate to reset old Data (in case it's loading lot of old data)

Let us know if you stilll have the issue after this tests

**Comment by jesterlol** [comment]
1. Yes
2. Yes
3. Yes
4. Did it

**Comment by Lyopheme** [comment]
same problem (large FPS drops each min), lot of people around me having the same issue

**Comment by l1amm** [comment]
I have no freezing problems, so a little hard to be of any help on this.

**Comment by Razorwynd** [comment]
I always thought it had something to do with the sync because I can emulate the freeze by turning on and off the sync feature...

**Comment by Road-block** [comment]
> I always thought it had something to do with the sync because I can emulate the freeze by turning on and off the sync feature...

Can you give my fork a try @Razorwynd   
I'm looking for people that can consistently reproduce the issue so I know if my changes fix it.  

https://github.com/Road-block/DPSMate  
I have made a pull request for the main-line but I'm sure Geigerkind would also be interested to know if this solves it before accepting changes.

**Comment by Razorwynd** [comment]
yeah i will test it out tonight... anything special i need to know? Do I just download and install as normal?

**Comment by Road-block** [comment]
Yes nothing special needed.

**Comment by Razorwynd** [comment]
@Road-block So I tried it last night in MC... the micro stutters seemed to be less abundant during regular game play (although there were still a few, maybe related to other things). However, I forgot to toggle sync off and on in an active raid setting, which is how I can purposefully induce these lag events. Ill keep testing it out.

**Comment by Road-block** [comment]
Yea thanks, I'm interested specifically in your experience with sync because that is the major change.

**Comment by Razorwynd** [comment]
No real problems with the stutter/lag since switching over. I hope to test your version on Vael tomorrow; I know that is a fight that can be difficult for combat parsing addons.

**Comment by Geigerkind** [comment]
Please report back if the change helped from Road-block!

**Comment by Razorwynd** [comment]
I think I mentioned somewhere that the change certainly helped with the periodic freezing...

**Comment by Mixuspidelix** [comment]
Since the whole thing has caught me right now, I ask again here. As soon as I actively shoot and sync, it takes quite a while for these stutter lags to begin. Even with the latest version. Did I do something wrong somewhere? Should I delete my Wtf folder with the corresponding SavedVariables to Dpsmate to stop this stuttering? Because Sync permanently disable can not be the solution of the whole.
