### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [Geigerkind/DPSMate#164]
[2017/12/17 19:43:01-1463]: DPSMate\DPSMate_Sync.lua:756: table index is nil
DPSMate\DPSMate_Sync.lua:756: in function `AbsorbsIn'
DPSMate\DPSMate_Sync.lua:1571: in function `?'
DPSMate\DPSMate_Sync.lua:361: in function `?'
DPSMate\DPSMate_DataBuilder.lua:649: in function <Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:649>

  ---

**Comment by Geigerkind** [comment]
Prolly some version mismatch, make sure that everyone uses the same version
