### ISSUE TITLE
"Uploading:Could not find RPLLVanilla.lua"

### ISSUE THREAD

**Issue by Aegion** [Geigerkind/DPSMate#165]
I cannot upload anything to your database because your Client cannot find the RPLLVanilla.lua, w/e that is.

Please help me upload my data.

Thanks.

https://imgur.com/lilxZTU
![clipboard01](https://user-images.githubusercontent.com/35350242/34849279-9e752eee-f72a-11e7-96ef-75a51bb7d414.jpg)

**Comment by l1amm** [comment]
This doesn't have anything to do with DPSMate... ?

**Comment by Geigerkind** [comment]
Doesnt belong here, hit me up on discord for such things
