### ISSUE TITLE
Missing option for rightclick reports

### ISSUE THREAD

**Issue by Hobrow** [Geigerkind/DPSMate#168]
Heya Shino,

I'd like to make a request to the report function of a single player.
By rightclicking on a person -> report -> chat channel

When doing this all information is instantly posted, which causes one to disconnect on the Lights Hope servers.
Since all other reports work with the delay function, I'd like to request the delay function to be added to the rightclick menu when reporting something.

Cheers,
Hobrow

**Comment by l1amm** [comment]
I'll work on adding delay function to this. :)

**Comment by Geigerkind** [comment]
This option exists: Basically once you click on Delay at report, its delay for everthing
