### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/DPSMate#172]
http://www.bilder-upload.eu/show.php?file=3eb5a9-1517693051.jpg

wenn ich in einem Schlachtzug bin - Sync aktiv ist und ich versuche zu resetten, dann erscheint dieser Fehler!

**Comment by Road-block** [comment]
Adding the full error stack.  
I'll check this.

```lua
[2018/02/06 11:58:59-4814-x1]: <unknown>:
<in C code>: in function `error'
AceComm-2.0\AceComm-2.0.lua:2711: in function `SendAddonMessage'
DPSMate\DPSMate_Sync.lua:54: in function <Interface\AddOns\DPSMate\DPSMate_Sync.lua:53>
DPSMate\DPSMate_Sync.lua:196: in function `StartVote'
DPSMate\DPSMate_Options.lua:774: in function `PopUpAccept'
<string>:"DPSMate_PopUp_Total:OnClick":2: in main chunk

  ---
```
Looks like it might be caused by an AceComm-2.0 embedded in another addon (DPSMate doesn't use it)

**Comment by Road-block** [comment]
Found the issue.  
I'll do a small pull request soon to fix this.
