### ISSUE TITLE
Can't watch at previous segments

### ISSUE THREAD

**Issue by Medicpack** [Geigerkind/DPSMate#173]
Whenever I try to display any previous fight, I'm getting an error window : 
Interface\AddOns\DPSMate\DPSMate.lua:608: attempt to index field `?' (a nil value)

Searched the internet for a fix but couldn't find anything. Not knowing what to do, here I am.
I'm using an english client on a french server, if that's of any relevance.

**Comment by Medicpack** [comment]
Upon further investigation, the issue seems to be happening with the "Healing and absorbs" mode only.

**Comment by Geigerkind** [comment]
Fixed
