### ISSUE TITLE
New parser, non-combat summons

### ISSUE THREAD

**Issue by Road-block** [Geigerkind/DPSMate#179]
DPSMate: Event not parsed yet, inform Shino! => You perform Summon Smolderweb.
DPSMate: Event not parsed yet, inform Shino! => You perform Summon Worg Pup.

😆

**Comment by Road-block** [comment]
DPSMate: Event not parsed yet, inform Shino! => Meshodve performs Fishing.

**Comment by Road-block** [comment]
DPSMate: Event not parsed yet, inform Shino! => Lythanias performs Call Pet.

**Comment by Road-block** [comment]
DPSMate: Event not parsed yet, inform Shino! => Winterfall Totemic performs Dazed on you.

**Comment by Road-block** [comment]
DPSMate: Event not parsed yet, inform Shino! => Bast casts Growl on Stormscale Warrior.

**Comment by Geigerkind** [comment]
Thanks, I think I fixed most of them, I kinda forgot to upload the update
Will do so today. Please close the tickets then if you cant reproduce this issue then :>
