### ISSUE TITLE
Parser Issue: Warlock Summons

### ISSUE THREAD

**Issue by neerau** [Geigerkind/DPSMate#184]
Event not parsed yet, Inform Shino! => Mangy Wolf hits Konzazt for 10.

Happens with all Warlock combat pets I have access too (Imp and Voidwalker). 

Would be nice to have the option to remove these warning messages from the chat, if possible.

**Comment by Geigerkind** [comment]
Which number does it print, int front this "X: Event not.."

**Comment by Geigerkind** [comment]
Should be fixed by now
