### ISSUE TITLE
Issues with parser and LUA errors

### ISSUE THREAD

**Issue by Branszin** [Geigerkind/DPSMate#186]
DPSMate: 17: Event not parsed yet, inform Shino! => You perform Fishing.

DPSMate: 19: Event not parsed yet, inform Shino! => Saltpillar's Thorns were resisted by Blackhand Veteran 

Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:2010: bad argument #1 to `strfind' (string expected, got nill)

This last error happens at odd times but it always happens when a party member dies.

**Comment by scottgreenup** [comment]
```
	if strfind(target, "%s") then return end
```

I think target is nil, and needs to be checked first. Maybe inserting this line beforehand?

```
    if target == nil then return end
```

**Comment by Geigerkind** [comment]
These events should not occour there...

**Comment by scottgreenup** [comment]
@Geigerkind Why did you close this ticket?

**Comment by Geigerkind** [comment]
Because I fixed this issue in the new build
