### ISSUE TITLE
When a enemy misses

### ISSUE THREAD

**Issue by Branszin** [Geigerkind/DPSMate#187]
![wowscrnshot_080918_182208](https://user-images.githubusercontent.com/25231167/43940499-c49db4a2-9c24-11e8-81c9-6b4fcc78ceb5.jpg)
![wowscrnshot_080918_184930](https://user-images.githubusercontent.com/25231167/43940500-c4b736e8-9c24-11e8-9c59-50dd3bb7fd20.jpg)

These errors would occur when something misses its attack against my character.

**Comment by Geigerkind** [comment]
I think I fixed that in the newest version, please test it

**Comment by Branszin** [comment]
No longer getting LUA errors when an enemy misses me, when a party member dies, or any parser warning when I cast fishing. I do get a parser warning when someone in my party dies but it's no longer a LUA error. Thank you. 
![wowscrnshot_081018_135142](https://user-images.githubusercontent.com/25231167/43980983-f887d204-9ca4-11e8-8d2e-d0236043300c.jpg)

**Comment by Geigerkind** [comment]
Foxed with the newest version
