### ISSUE TITLE
Spamming chat

### ISSUE THREAD

**Issue by Novodk** [Geigerkind/DPSMate#190]
It keeps spamming in chat like in the picture [here,](https://imgur.com/a/SrjMl5a) and on Chromaggus it uses more then 400 MB of ram and my game crashes.
Any fix for this?, i have tried to make a comlete reinstall, but that didnt work

**Comment by roanaes** [comment]
++ i have same issue in retrowow

**Comment by Mixuspidelix** [comment]
if you issue your sync, no spam will come. Unfortunately, then you have no sync with each other :s

**Comment by Geigerkind** [comment]
Fixed in newest version
