### ISSUE TITLE
Error: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by ghost** [Geigerkind/DPSMate#192]
Hi, 

I have this message spamming the chat when i enable DPSMate:
ERROR: Interface\Addons\DPSMate\DPSMate_Sync.lua:1352:attempt to concatenate a nil value

Dunno if its me or not
Sincerely,

**Comment by Yesnig** [comment]
So i updated DPS mate on the latest version and still have this problem . It appears periodically hope you could fix it somehow would be cool thanks for your work so far

**Comment by lvangh** [comment]
Same issue with latest version.

**Comment by Amuoeba** [comment]
FYI in my case reinstalling DPSmate solved the problem.

**Comment by Geigerkind** [comment]
Should be dealt with
