### ISSUE TITLE
Hunt Pet auto attack damage record on client but not when uploaded to LegacyPlayers

### ISSUE THREAD

**Issue by Kajjan112** [Geigerkind/DPSMate#193]
LegacyPlayers is completely missing pet AutoAttack when checking the logs vs Addon. Every other source of damage from everything else matched up from client to LegacyPlayers except the missing pet damage.
Guessing it could be because both character and pet is called "AutoAttack" at some point in the merge maybe?

**Comment by Kajjan112** [comment]
![wowscrnshot_082318_010202](https://user-images.githubusercontent.com/31672709/44495887-198db500-a672-11e8-97de-1a2f0a177828.jpg)
![dmgdone](https://user-images.githubusercontent.com/31672709/44495888-1abee200-a672-11e8-8ac8-b44eac46c6d2.png)

**Comment by Kajjan112** [comment]
So i decided to download whatever the latest version was here on Github and pet damage isn't tracked at all now?

**Comment by Kajjan112** [comment]
So i downloaded the latest version and now pet damage isn't even recorded for my own dpsMate.
Guessing the other guys who uploaded to LegacyPlayers had the same version. 
But this brings it to the next question. Why isn't pet damage recorded on the latest version?

**Comment by Kajjan112** [comment]
Also worth to mention is that the other hunter in the raid atleast had his pets "bite" and "claw" in the legacy logs but also missing pet autoattack

**Comment by Geigerkind** [comment]
Depends on many factors that LP picks it up. Anyways check on top right the cogwheel if merge pets is enabled etc.
For now I will close this ticket. Thats not the right place for LP issues. If you keep having issues, report them on discord.
