### ISSUE TITLE
Error with Grounding Totem

### ISSUE THREAD

**Issue by Nixxen** [Geigerkind/DPSMate#195]
Not sure if this is the correct place to post about this, but I'll just leave a note in case anyone who is interested finds it.

During a LBRS run where arcane missiles destroyed a grounding totem a text message popped up in the chat.
It disappeared rather quickly from the log so this won't be exact, but it was something along the lines of:
"Event not parsed correctly, Inform Shino: Grounding totem was destroyed."

Do note that the above is probably way off, but in essence I think it was about the grounding totem being destroyed not being a registered event or something.
The same thing also happened later for Windfury Totem.

Edit:
Seems it happens with all totems.

**Comment by Geigerkind** [comment]
Doesnt it say which event msg? like a prefix ?

**Comment by Geigerkind** [comment]
Closing because of no response :<
