### ISSUE TITLE
1285: Table index is nill error

### ISSUE THREAD

**Issue by lvangh** [Geigerkind/DPSMate#196]
I was in an instance by myself and just killed a mob and this error popped up. 

I just recently deleted all DPSMate folders in the \Addons folder AND also deleted the files under my WTF\Accoutname folder for a complete 'reset'. Then I downloaded the latest version. 

![image](https://user-images.githubusercontent.com/19690096/46519549-95f8e380-c82d-11e8-8de3-e3bf6b92fab7.png)

**Comment by Geigerkind** [comment]
Fixed
