### ISSUE TITLE
Event not parsed yet => Deep Wound

### ISSUE THREAD

**Issue by sykst** [Geigerkind/DPSMate#197]
![image](https://user-images.githubusercontent.com/42090709/46527273-0422c200-c891-11e8-9dbe-99ef88452724.png)

![image](https://user-images.githubusercontent.com/42090709/46527299-13097480-c891-11e8-862e-5aa59f1bf44e.png)
![image](https://user-images.githubusercontent.com/42090709/46527308-1b61af80-c891-11e8-81c9-85d9429ad331.png)

**Comment by sykst** [comment]
also,

![image](https://user-images.githubusercontent.com/42090709/46528134-51079800-c893-11e8-9c73-3fbb06418893.png)
![image](https://user-images.githubusercontent.com/42090709/46528155-5d8bf080-c893-11e8-982f-520e5605a15d.png)

**Comment by lvangh** [comment]
Seeing this w/ latest version too.

**Comment by sykst** [comment]
I've been seeing it only since downloading it today. There is quite a few
like that, for different spells, me, pet, w/e. @shino, you want me to post
them all?

**Comment by Geigerkind** [comment]
Fixed, thanks!
