### ISSUE TITLE
Keybind Functionality

### ISSUE THREAD

**Issue by ZetoxZ** [Geigerkind/DPSMate#2]
Add Keybinds functionality such as 

1. Hide / Hide Show Window
2. Disable / Enable
2. Reset Meter

(This will be helpful for many who don't to show the minimap icon to access the addon, rather through keybinds.)

**Comment by Geigerkind** [comment]
UUh, I even implmented that in TBC and WOTLK but apparently forgot it for vanilla.

Will add it this weekend!

cheers!

**Comment by ZetoxZ** [comment]
Great work :)
