### ISSUE TITLE
DPSMATE\DPSMATE_Parser.lua:531 error

### ISSUE THREAD

**Issue by shamanmike** [Geigerkind/DPSMate#200]
Even after updating the addon with the fix you dropped 13 days ago, I'm still getting the same error as the warlock from before. I'm getting it on my shaman with healing stream totem though. Do you think it's possible to fix that?
![image](https://user-images.githubusercontent.com/8785423/47114656-c17fc300-d25c-11e8-86b5-f347d171312c.png)

Thanks in advance for the help!

**Comment by neckroRO** [comment]
I get the same error. Meanwhile did you figure out what happend?

**Comment by Geigerkind** [comment]
Fixed
