### ISSUE TITLE
Same name pet bugs DPSmate out

### ISSUE THREAD

**Issue by nanachiez** [Geigerkind/DPSMate#201]
My pet has the same name as myself, for PVP reasons, and any time i bring my pet out, it'll bug DPSmate until I clear my WTF SavedVariables. I will not be able to see my own DPS. I love DPSmate and I don't want to disband my Broken Tooth :(, would appreciate a fix for this so incredibly much. <3

**Comment by Geigerkind** [comment]
Unfortunatly this is not possible to fix in Vanilla, sorry.
