### ISSUE TITLE
Not enough storage is available to process this command. 

### ISSUE THREAD

**Issue by asandersimon** [Geigerkind/DPSMate#202]
So, today when i tried to login i keep getting wowerror with DPSMate activated, 

https://gyazo.com/0269ecc71035842243288f6b6a09dbba

Is there a solution to this problem?

**Comment by raethkcj** [comment]
I'm not sure how to prevent it, but you can temporarily fix it by going to the folder `World of Warcraft/WTF/Account/<Account Name>/<Server Name>/<Character Name>/SavedVariables` and deleting `DPSMate.lua` and `DPSMate.lua.bak`.

**Comment by Geigerkind** [comment]
You need to increase your addon memory. And be sure to reset DPSMate regularily as it blows up in memory quiet quickly.
