### ISSUE TITLE
interrupt-error

### ISSUE THREAD

**Issue by Mixuspidelix** [Geigerkind/DPSMate#203]
https://www.bilder-upload.eu/bild-b10c00-1540238296.jpg.html

**Comment by Geigerkind** [comment]
Link broken :<

**Comment by Mixuspidelix** [comment]
[URL=https://www.directupload.net/file/d/5291/p4dmwoac_jpg.htm][IMG]https://s15.directupload.net/images/181204/temp/p4dmwoac.jpg[/IMG][/URL]

**Comment by Geigerkind** [comment]
Should be fixed
