### ISSUE TITLE
WANTED: Localization - (zhTW/zhCN) - Mandarin

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#21]
Hey!
I am looking for someone to translate DPSMate to this language.

What needs to be done:
- The databases need to be updated (Can be done by script)
- The locale file needs to be updated (By hand)
- The parser needs to be updated (By hand)
- Some other bits here and there

Please hit me up or comment here if you are interested in helping!
You will be mentioned forever in the about tab of DPSMate ofcourse!

cheers!

**Comment by jokers-x** [comment]
I can do it.

**Comment by Geigerkind** [comment]
Sweet!
Ok, let's start with the easy translations first:
Could you download this file and translate the **right** site?
https://github.com/Geigerkind/DPSMate/blob/master/localization/zhTW_CN.lua

Upload it here again then please.
Also, I can't really make the difference out between zhTW and zhCN, is it something similiar or completly differnent and what would you translate?

cheers!

**Comment by Geigerkind** [comment]
Hey!
I just updated the tooltips, can I ask you to translate these few strings as well?
-- Newly added:
DPSMate.L["tttop"] = "Top "
DPSMate.L["ttdamage"] = " Damage"
DPSMate.L["tthealing"] = " Healing"
DPSMate.L["ttpet"] = " Pet"
DPSMate.L["ttpet2"] = "Pet: "
DPSMate.L["ttabilities"] = " Abilities"
DPSMate.L["ttattacked"] = " Attacked"
DPSMate.L["tthealed"] = " Healed"
DPSMate.L["ttinterrupt"] = " Interrupt"
DPSMate.L["ttinterrupted"] = " Interrupted"
DPSMate.L["ttdispelled"] = " Dispelled"
DPSMate.L["ttabsorbed"] = " Absorbed"
DPSMate.L["ttabsorb"] = " Absorb"
DPSMate.L["ttthreat"] = " Threat"

cheers!

**Comment by Darkmiao** [comment]
Greetings,

I have done the 2nd part - <The locale file needs to be updated (By hand)>.
My friend in Covenant made a request like 1 month ago so I did it.
I've tested it both in Chinese and English client, works pretty well in English client,
but in Chinese client, it pops up errors all the time.
I think the 3rd part <parser> should be translated too to make it well functioning in Chinese client.

Check the link below, I have pushed it onto github: 
https://github.com/Darkmiao/zhCN_localization/blob/master/zhCN_DPSMate.lua

**Comment by Geigerkind** [comment]
Yes, this is just the first part. Thank you very much!

**Comment by Darkmiao** [comment]
DPSMate.L["tttop"] = "顶端 "
DPSMate.L["ttdamage"] = " 伤害"
DPSMate.L["tthealing"] = " 治疗"
DPSMate.L["ttpet"] = " 宠物"
DPSMate.L["ttpet2"] = "宠物: "
DPSMate.L["ttabilities"] = " 技能"
DPSMate.L["ttattacked"] = " 被攻击"
DPSMate.L["tthealed"] = " 被治疗"
DPSMate.L["ttinterrupt"] = " 打断"
DPSMate.L["ttinterrupted"] = " 被打断"
DPSMate.L["ttdispelled"] = " 被驱散"
DPSMate.L["ttabsorbed"] = " 被吸收"
DPSMate.L["ttabsorb"] = " 吸收"
DPSMate.L["ttthreat"] = " 仇恨"

**Comment by Geigerkind** [comment]
Sweet, thanks!
I am going to have time to code on DPSMate again on 20 March. I'd like to finish the translations in this span there. Would be nice if we could arrange something to do the parser translation together, cause these signs are basically just pictures for me :)

cheers!

**Comment by Darkmiao** [comment]
You are welcome, great job on DPSMate, highly estimated by my friends in the guild.

Actually, I am on new year vacation and available till February 5.
Plz send me the file and I will see what i can do.

**Comment by Geigerkind** [comment]
Well, it is about the parser, but depending on the language it is completly different. So If you have knowledge in programming, you might as well take the parser and translate it with your combat log strings, else I will need a link to a chinise client and someone I can ask what something means^^

**Comment by Darkmiao** [comment]
This is a link to Chinese client: http://pan.baidu.com/s/1nuGfdd3
Most used cloud drive in China.
You may wanna sign in and download the cloud client, lots of porns in it.
😆 

And about the parser, still don't have a clue what to do.

**Comment by Geigerkind** [comment]
Is there any link where I don't have to sign in^^?

**Comment by Darkmiao** [comment]
yeah, should be, i ll try to find it, get back to you tomorrow

**Comment by Geigerkind** [comment]
Thank you

**Comment by Darkmiao** [comment]
`-- You hit Blazing Elemental for 187.
-- 你击中 火眼莫德雷斯 造成121点伤害。                                                           --zhCN client combat log
-- (You你)(hit击中) (target) (cause造成)(121)(unit点)(damage伤害)(。)                --translated for you

-- You crit Blazing Elemental for 400.
-- 你对 火眼莫德雷斯 造成562的致命一击伤害。                                                 --zhCN client combat log
-- (you你)(to对) (target) (cause造成)(562)(of的)(crit致命一击)(damage伤害)(。)  --translated for you

function DPSMate.Parser:SelfHits(msg)
	t = {}
	for a,b,c,d in strgfind(msg, "you (%a%a?)\it (.+) for (%d+)%. %((%d+) absorbed%)") do
		DB:SetUnregisterVariables(tnbr(d), "AutoAttack", self.player)
	end
end`

I just pull out the codes from lign 13 to lign 19 of the file DPSMate_ParserENUS.lua.
You can see that in english client, "hit"&"crit" are the very same format, but not the case in zhCN client.
Could you plz find a way that just let the localization group do the localization part?

Btw, i could not find a link to download the client directly.

**Comment by Geigerkind** [comment]
Hey!
Ya, that is why the structure is a little different for every language.
What do you mean with find a way to let this group do it ?

That is unfortunate, will if I can find another way :>
cheers!

**Comment by Darkmiao** [comment]
I am not sure if I have the ability to do the parser part, cause I am not professional programmer.

**Comment by Geigerkind** [comment]
Hey!
One question: Did you make sure that the instance translation for Molten Core, Duskwood, Azshare etc. are matching with the ones ingame?

cheers!

**Comment by Geigerkind** [comment]
Do you happen to know a mandarin wow 1.12 database?

**Comment by JJasonYuen** [comment]
http://cn.60wdb.com/
Its a mandarin wow 1.12 database website and it also contains  corresponding english contents.

**Comment by Geigerkind** [comment]
sweet thy!

**Comment by Geigerkind** [comment]
Hey!
Can I ask you to translate these? 
These are the schools of the abilities.

["fire"] = 3,
["holy"] = 7,
["arcane"] = 6,
["shadow"] = 5,
["nature"] = 4,
["frost"] = 2,
["physical"] = 1,

cheers!

**Comment by JJasonYuen** [comment]
["火焰"] = 3,
["神圣"] = 7,
["奥术"] = 6,
["暗影"] = 5,
["自然"] = 4,
["冰霜"] = 2,
["物理"] = 1,

**Comment by Geigerkind** [comment]
Thank you!

**Comment by 123yinlunwei** [comment]
Looking forward to

**Comment by Geigerkind** [comment]
I really need help to implement the parser. I have the strings but you need to tell me what is actually the ability, the cause, the number etc.

So if anyone has time to answer me this questions please hit me up and we can talk on ts, discord or skype.

**Comment by 123yinlunwei** [comment]
Don't know how to help you?Can I try it on the BBS in China to help you find you need!

**Comment by Geigerkind** [comment]
Hey!
For example: With this string I struggle to identify who was interrupted and what was interrupted.
So is the first (.+) "A placeholder" the ability or the guy that was interrupted:

你打断了(.+)的(.+)。

cheers!

**Comment by Geigerkind** [comment]
Just such questions, it is really difficult to tell for me^^

**Comment by Geigerkind** [comment]
Same question: What is the ability and who has gotten it:

(.+)受到(.+)的伤害(.*)

**Comment by Geigerkind** [comment]
If you have discord, please join https://discord.gg/m85ar for faster communitcation.

**Comment by devilyer** [comment]
I think the code you need can be found in the GlobalStrings.lua file,

Https://drive.google.com/open? Id=0B8r0M7kRnf67d2RzZTczRUJ0VUk (zhCN)

Https://www.townlong-yak.com/framexml/1.12.1/GlobalStrings.lua (enUs)

**Comment by Geigerkind** [comment]
I do have the global strings. I just don't know which placeholder may represent what.
Going to add you koro!

**Comment by Geigerkind** [comment]
What does it say when a mob crushes you?

**Comment by devilyer** [comment]
enUs  ==    (.+) hits you for (.+).(curshing)
zhCN ==    (.+)击中你造成(.+)点伤害。（碾压）

**Comment by Geigerkind** [comment]
Thanks!

**Comment by Geigerkind** [comment]
Will have the parser done within 1.5H. Please download the master then and test it, in case I understood sth wrong.

cheers!
