### ISSUE TITLE
WANTED: Localization - frFR - French

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#22]
Hey!
I am looking for someone to translate DPSMate to this language.

What needs to be done:
- The databases need to be updated (Can be done by script)
- The locale file needs to be updated (By hand)
- The parser needs to be updated (By hand)
- Some other bits here and there

Please hit me up or comment here if you are interested in helping!
You will be mentioned forever in the about tab of DPSMate ofcourse!

cheers!

**Comment by ITTranslator** [comment]
Would be glad to help with this! I'm a professional translator and could try to find a bit of room in my schedule for this.
[Anthony](http://www.at-it-translator.com)

**Comment by ITTranslator** [comment]
Excellent, thanks for the file. I should have the French translation ready within the next few days :)

**Comment by Geigerkind** [comment]
Great, thank you!

**Comment by ITTranslator** [comment]
OK, I tried to update the file with the French text. I've been working with my usual translation tool, so I hope it didn't mess up the format or anything. If something looks out of place, just let me know.

**Comment by Geigerkind** [comment]
Sweet, can you attach the file here, so I can merge it with the master branch?

**Comment by ITTranslator** [comment]
Let me see... will that do?
[frFR.zip](https://github.com/Geigerkind/DPSMate/files/720897/frFR.zip)

**Comment by Geigerkind** [comment]
Yes Sir, thank you!
Now there is not a lot to do anymore for you. But you could help me a lot if you could tell what everything means in these sentences.
Who, to Whom, With What Ability, Hit him with How much, TargetAbility

This could look like this "...."; -- Who, Ability, Whom, TargetAbility

If you don't know what is what just leave it how it is, I will figure it out by testing then^^

[GlobalStrings-FR-1.12.zip](https://github.com/Geigerkind/DPSMate/files/721024/GlobalStrings-FR-1.12.zip)

**Comment by Geigerkind** [comment]
Hey!
I just updated the tooltips, can I ask you to translate these few strings as well?
-- Newly added:
DPSMate.L["tttop"] = "Top "
DPSMate.L["ttdamage"] = " Damage"
DPSMate.L["tthealing"] = " Healing"
DPSMate.L["ttpet"] = " Pet"
DPSMate.L["ttpet2"] = "Pet: "
DPSMate.L["ttabilities"] = " Abilities"
DPSMate.L["ttattacked"] = " Attacked"
DPSMate.L["tthealed"] = " Healed"
DPSMate.L["ttinterrupt"] = " Interrupt"
DPSMate.L["ttinterrupted"] = " Interrupted"
DPSMate.L["ttdispelled"] = " Dispelled"
DPSMate.L["ttabsorbed"] = " Absorbed"
DPSMate.L["ttabsorb"] = " Absorb"
DPSMate.L["ttthreat"] = " Threat"

cheers!

**Comment by ITTranslator** [comment]
Here go the extra translations:
DPSMate.L["tttop"] = "Haut "
DPSMate.L["ttdamage"] = " Dégâts"
DPSMate.L["tthealing"] = " Soins"
DPSMate.L["ttpet"] = " Domestique"
DPSMate.L["ttpet2"] = "Domestique: "
DPSMate.L["ttabilities"] = " Compétences"
DPSMate.L["ttattacked"] = " Attaqué(e)"
DPSMate.L["tthealed"] = " Soignée(e)"
DPSMate.L["ttinterrupt"] = " Interruption"
DPSMate.L["ttinterrupted"] = " Interrompu"
DPSMate.L["ttdispelled"] = " Levé"
DPSMate.L["ttabsorbed"] = " Absorbé"
DPSMate.L["ttabsorb"] = " Absorber"
DPSMate.L["ttthreat"] = " Menace"

Might need a bit more time for the other request, it's quite a big task actually to figure everything out and write it down :o

**Comment by Geigerkind** [comment]
Thank you very much!
Don't worry about it too much if you can't read it out directly. I thought a native speaker could tell by the structure. I will need to download the client anyway and test everything.

cheers!

**Comment by Kalandras** [comment]
Can't wait the update <3

**Comment by Geigerkind** [comment]
Hey!
One question: Did you make sure that the instance translation for Molten Core, Duskwood, Azshare etc. are matching with the ones ingame?

cheers!

**Comment by Geigerkind** [comment]
Hey!
Can I ask you to translate these? 
These are the schools of the abilities.

["fire"] = 3,
["holy"] = 7,
["arcane"] = 6,
["shadow"] = 5,
["nature"] = 4,
["frost"] = 2,
["physical"] = 1,

cheers!

**Comment by Geigerkind** [comment]
Done. Needs testing

**Comment by Geigerkind** [comment]
Wait, still need this list!
["fire"] = 3,
["holy"] = 7,
["arcane"] = 6,
["shadow"] = 5,
["nature"] = 4,
["frost"] = 2,
["physical"] = 1,
