### ISSUE TITLE
Random names

### ISSUE THREAD

**Issue by Hexxagon** [Geigerkind/DPSMate#225]
People are given random names in my DPSmate. They can be "sandfury slave" or they can be someone from an old party. It seems to track dmg and so on fine, but gives almost everyone random names. Some are names from the party but on the wrong person. Any fix to this?

**Comment by armoha** [comment]
If you place WoW to directory with permissions, like `Program Files`, you should either run WoW as administrator, or change the folder's security settings to allow writting. If not, DPSMate can't write its saved variables so random names are shown.
