### ISSUE TITLE
Hunter: Mend Pet

### ISSUE THREAD

**Issue by Fixxxer11530** [Geigerkind/DPSMate#228]
INFO: Interface\AddOns\DPSMate\enUS\DPSMate_ParserENUS.lua: 1777: attempt to perform arithmetic on local 'amount' (a nil value)

**Comment by Stuleo** [comment]
Hi, i got the same error message.
It occures when my voidwalker uses "Consume Shadows" and heals himself.

CombatLog text:
Konthyk gains Consume Shadows
Konthyk gains 63 health from Konthyk'y Consume Shadows

After that the error message appears

**Comment by Bloodmoor269** [comment]
So, this was fixed or what, why 1777 still popin?
