### ISSUE TITLE
WANTED: Localization - esES - Spanish

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#23]
Hey!
I am looking for someone to translate DPSMate to this language.

What needs to be done:
- The databases need to be updated (Can be done by script)
- The locale file needs to be updated (By hand)
- The parser needs to be updated (By hand)
- Some other bits here and there

Please hit me up or comment here if you are interested in helping!
You will be mentioned forever in the about tab of DPSMate ofcourse!

cheers!

**Comment by loonatiko** [comment]
Let me help 😀

**Comment by Geigerkind** [comment]
Sweet!
Ok, let's start with the easy translations first:
Could you download this file and translate the right site?
https://github.com/Geigerkind/DPSMate/blob/master/localization/esES.lua

Upload it here again then please.
cheers!

**Comment by Geigerkind** [comment]
Hey!
I just updated the tooltips, can I ask you to translate these few strings as well?
-- Newly added:
DPSMate.L["tttop"] = "Top "
DPSMate.L["ttdamage"] = " Damage"
DPSMate.L["tthealing"] = " Healing"
DPSMate.L["ttpet"] = " Pet"
DPSMate.L["ttpet2"] = "Pet: "
DPSMate.L["ttabilities"] = " Abilities"
DPSMate.L["ttattacked"] = " Attacked"
DPSMate.L["tthealed"] = " Healed"
DPSMate.L["ttinterrupt"] = " Interrupt"
DPSMate.L["ttinterrupted"] = " Interrupted"
DPSMate.L["ttdispelled"] = " Dispelled"
DPSMate.L["ttabsorbed"] = " Absorbed"
DPSMate.L["ttabsorb"] = " Absorb"
DPSMate.L["ttthreat"] = " Threat"

cheers!

**Comment by Geigerkind** [comment]
I guess no interest.
