### ISSUE TITLE
WANTED: Localization - ruRU - Russian

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#24]
Hey!
I am looking for someone to translate DPSMate to this language.

What needs to be done:
- The databases need to be updated (Can be done by script)
- The locale file needs to be updated (By hand)
- The parser needs to be updated (By hand)
- Some other bits here and there

Please hit me up or comment here if you are interested in helping!
You will be mentioned forever in the about tab of DPSMate ofcourse!

cheers!

**Comment by Geigerkind** [comment]
@M2us seems to work on a russian translation :)
https://github.com/M2us/DPSMate

Imported from older comment:
I can help with the Russian language.
Here spell.dbc (spells) and GlobalStrings.lua (Combat log)
Just I am ready to test in Russian. I can provide more files for comparison.
Link: https://drive.google.com/open?id=0B2RWjLl8UkfxMld4c05INzV2UXM

**Comment by Geigerkind** [comment]
Hey!
I just updated the tooltips, can I ask you to translate these few strings as well?
-- Newly added:
DPSMate.L["tttop"] = "Top "
DPSMate.L["ttdamage"] = " Damage"
DPSMate.L["tthealing"] = " Healing"
DPSMate.L["ttpet"] = " Pet"
DPSMate.L["ttpet2"] = "Pet: "
DPSMate.L["ttabilities"] = " Abilities"
DPSMate.L["ttattacked"] = " Attacked"
DPSMate.L["tthealed"] = " Healed"
DPSMate.L["ttinterrupt"] = " Interrupt"
DPSMate.L["ttinterrupted"] = " Interrupted"
DPSMate.L["ttdispelled"] = " Dispelled"
DPSMate.L["ttabsorbed"] = " Absorbed"
DPSMate.L["ttabsorb"] = " Absorb"
DPSMate.L["ttthreat"] = " Threat"

cheers!

**Comment by M2us** [comment]
Hi. Damage Done is done.
It's desirable to test.
Oh... next, damage taken. =(

**Comment by Geigerkind** [comment]
Sweet, if you need help, hit me up! But you seem to be able to cope with it yourself.
Really looking forward to it.
Thank you!

**Comment by M2us** [comment]
Ok. ^___^

**Comment by M2us** [comment]
I don't understand, where this string in Global Strings.lua? 
https://github.com/Geigerkind/DPSMate/blob/master/DPSMate/enUS/DPSMate_ParserENUS.lua#L713
or this ( (,+) gains (%d+) health from (.+)% ) two strings? 
PERIODICAURAHEALOTHEROTHER = "%s gains %d health from %s's %s."; 
PERIODICAURAHEALSELFOTHER = "%s gains %d health from your %s.";

**Comment by Geigerkind** [comment]
When I tested it it there were lots of different cases. Maybe this event is just a private server thing, but I also didnt find it in the global strings back then.
Seems to be some special case where X heals himself with an periodic ability

**Comment by M2us** [comment]
Done.
But, now, need to update to last version... i tired. =(

**Comment by Geigerkind** [comment]
Better don't update, I am going to merge properly once you are done, since I changed the system entirely.

Have you tested all combat log events if they work?

Thanks for your hard work!

(Also did you see that I added a few locals for tooltip processing?)

cheers!

**Comment by M2us** [comment]
don't update? But parser have new strings. This
for who, whom, what in strgfind(msg, "(.-) interrupts (.+)'s (.+)%.") do

and this
for whom, what in strgfind(msg, "You interrupt (.+)'s (.+)%.") do

**Comment by Geigerkind** [comment]
Ah, the parser updates^^
Nah, I thoght you wanted to merge with the master branch, which is currently a mess^^
Well hit me up, when you are ready to go, need some time on top of that to fix it then for legacy logs though.

cheers!

**Comment by Geigerkind** [comment]
Did you delete your repository or made it private?
Can you provide access for me :> ?

**Comment by M2us** [comment]
Delete. 
I used new fork and added ruRU locale.
https://github.com/M2us/DPSMate
But, I don't understand. 
ruRU files doesn't work. I added ruRU to AceLocales... i really don't understand, why ru files not uses
https://github.com/M2us/DPSMate/blob/master/DPSMate/libs/AceLocale/AceLocale-2.2.lua#L391

**Comment by Geigerkind** [comment]
The name in the toc file is wrong. You called the locale file ruRu.lua, in the .toc file it states ruRU.lua though.

**Comment by M2us** [comment]
no, not work.

**Comment by Geigerkind** [comment]
Did you also restarted the game after you renamed it?

**Comment by M2us** [comment]
Of course. I renamed file and then start the game.
And, (before renamed) I have some error
DPSMate\libs\AceLocale\AceLocale-2.2.lua:303:bad argument #1 to 'pairs' (table expected, got nil)

**Comment by Geigerkind** [comment]
Try adding this to the Babble Spell file before Debug(true

BabbleSpell:RegisterTranslations("enUS", function() 
local temp = {}
for c,_ in pairs(spellIcons) do
	temp[c] = true
end
return temp end)

**Comment by M2us** [comment]
No. Interface in eng, but some interface elements rus. And this error: DPSMate\libs\AceLocale\AceLocale-2.2.lua:303:bad argument #1 to 'pairs' (table expected, got nil)

**Comment by M2us** [comment]
Hm... if I set Revision in ruRU Babble-Boss, Babble-Spell and NPCDB like in deDE version,
Then I have new error:
DPSMate_ruRU\Babble-Boss-2.3_ruRU.lua:320: attempt to call method '?' (a nil value)

**Comment by Geigerkind** [comment]
Ah, ya that is correct so that it updates.
I am currently looking through it and I am wondering about the very same part

**Comment by M2us** [comment]
sorry, 2 errors:
Error:  attempt to call method `?' (a nil value)
AddOn: DPSMate_ruRU
File: Babble-Boss-2.3_ruRU.lua
Line: 320
Count: 1
--------------------------------------------------
Error:  attempt to call method `RegisterTranslations' (a nil value)
AddOn: DPSMate_ruRU
File: NPCDB-1.0_ruRU.lua
Line: 27
Count: 1

**Comment by Geigerkind** [comment]
Ok, I guess I have messed up something in the core there.
I will sleep over this and attempt to fix it until next weekend (Unfortunately I can only work on weekends on my addons)

If the translation is done so far I will migrate it into the next version and tell you then.

cheers!

**Comment by M2us** [comment]
No, translation is done.
I change revision and rename ruRu.lua to ruRU.lua.

So, my work is over. =)

**Comment by Geigerkind** [comment]
Aight, I will integrate it then on the next weekend.
Thank you so much!

**Comment by M2us** [comment]
If we ever meet, you buy me a beer. xDDDD

**Comment by Geigerkind** [comment]
Sure :D

**Comment by Geigerkind** [comment]
Hey!
One question: Did you make sure that the instance translation for Molten Core, Duskwood, Azshare etc. are matching with the ones ingame?

cheers!

**Comment by M2us** [comment]
Yes. I took them from client.

Can i remove fork?

and update https://github.com/Geigerkind/DPSMate/blob/master/DPSMate_ruRU/ruRu.lua
change ruRu to ruRU
<<if (GetLocale() == "koKR") then>> to 
<<if (GetLocale() == "ruRU") then>> xDDDDD
and update text from https://github.com/M2us/DPSMate/blob/master/DPSMate_ruRU/ruRU.lua

**Comment by Geigerkind** [comment]
Yes, will do it, thy : >

**Comment by Geigerkind** [comment]
Updated. With the next build update it will be available even for Legacy Logs.
Thank you very much!

**Comment by Geigerkind** [comment]
Hey!
Can I ask you to translate these? 
These are the schools of the abilities.

["fire"] = 3,
["holy"] = 7,
["arcane"] = 6,
["shadow"] = 5,
["nature"] = 4,
["frost"] = 2,
["physical"] = 1,

cheers!

**Comment by shikulja** [comment]
> Hey!
> Can I ask you to translate these?
> These are the schools of the abilities.
> 
> ["fire"] = 3,
> ["holy"] = 7,
> ["arcane"] = 6,
> ["shadow"] = 5,
> ["nature"] = 4,
> ["frost"] = 2,
> ["physical"] = 1,
> 
> cheers!

огонь
свет
тайная
тьма
природа
лед
физический (урон) (damage) \ физическая (сила) (power)

**Comment by shikulja** [comment]
RESISTANCE_TYPE0 = "броня";
RESISTANCE_TYPE1 = "свет";
RESISTANCE_TYPE2 = "огонь";
RESISTANCE_TYPE3 = "природа";
RESISTANCE_TYPE4 = "лед";
RESISTANCE_TYPE5 = "тьма";
RESISTANCE_TYPE6 = "тайная магия";
