### ISSUE TITLE
Question: So it's going to be like this from now on?

### ISSUE THREAD

**Issue by kev41** [Geigerkind/DPSMate#35]
I also get errors that I never had before.

![dpsmatewuitface](https://cloud.githubusercontent.com/assets/21115526/22311007/c2e33638-e351-11e6-8fff-622b585d410e.jpg)

**Comment by kev41** [comment]
Using the 1 folder with everything in it wont load the addon.

**Comment by Geigerkind** [comment]
Please don't download the master branch, download the release versions!

https://github.com/Geigerkind/DPSMate/releases
