### ISSUE TITLE
Im getting this error

### ISSUE THREAD

**Issue by konbizz** [Geigerkind/DPSMate#36]
This from imp error frame:
Error:  attempt to call global `strmatch' (a nil value)
AddOn: DPSMate
File: LibStub.lua
Line: 14
Count: 1

And

This in chat:
Interface/addon/dpsmate/dpsmate_parser.lua537: attemp to index field "?" (a nil value)

**Comment by Geigerkind** [comment]
Please read the threads. DONT use the master branch, use the release versions!

https://github.com/Geigerkind/DPSMate/issues/35
