### ISSUE TITLE
MBB+DPSMate

### ISSUE THREAD

**Issue by Artur91425** [Geigerkind/DPSMate#38]
Does not work correctly minimap button with addon MBB. If you start to drag DPSMate button, it drags all the buttons for a left. Button inside the addon MBB should be motionless.
![bandicam 2017-01-28 02-49-15-593](https://cloud.githubusercontent.com/assets/24303693/22391955/a466fd24-e505-11e6-9f84-0c8083f7d4c9.jpg)
P.S. i use original MBB 0.312

**Comment by Geigerkind** [comment]
I removed DPSMate button from the bag. You can hide it then in the next version if you want
