### ISSUE TITLE
B90: Hunter pet damage no longer visible

### ISSUE THREAD

**Issue by DeTosc** [Geigerkind/DPSMate#39]
Hello,
since release B90, DPSMate no longer shows the damage of the pet pf my hunter, server Elysium Darrowshire PvE. I've tried with a cat (renamed) and a carrion bird with the default name.

**Comment by DeTosc** [comment]
And now it works again, ... I will investigate further and come back. Maybe switching pets via the stable master needs a relog?

**Comment by DeTosc** [comment]
Ok, B90 is working fine for hunter pets as long as you do NOT:
- Take a flight
- Switch pets at the stable master

After switching pets at the stable master, dpsmate will no longer show the damage of the (new) pet. 
You have to log out, log in with another char, log in with the hunter and it works again.
It is not enough to just log out / log in with the hunter.

**Comment by Geigerkind** [comment]
Fixed, will come with the new build in (roughly 6 weeks or so)
