### ISSUE TITLE
Nil Value Error

### ISSUE THREAD

**Issue by paintballrefjosh** [Geigerkind/DPSMate#43]
Just downloaded the addon a couple days ago.  If I die and hit the "release spirit" button I get the following error and am unable to release:

`Interface\AddOns\DPSMate\DPSMate_dataBuilder.lua:2297: attempt to index field 'EDT' (a nil value)`

I also noticed the same thing happens every time I kill a mob.

**Comment by Geigerkind** [comment]
You are probably using the development version, not the release version.
