### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by qVortex** [Geigerkind/DPSMate#44]
Hi Shino i like ur addon thank you, but laterst version i downloaded just bugged or what? http://i.imgur.com/tJtQkCw.jpg.

http://i.imgur.com/p9xduqB.jpg - addon record is working but cannot see any Graphs (also when Test mode enabled).

Using enUS client with clean WDB.

**Comment by Geigerkind** [comment]
I also wrote you that in the thread but here again for everyone else to see it:
Download the releases NOT the master branch. Use the links I provided on Legacy Logs and the thread.
The master branch is solely for development purposes and thus is not always working!
cheers!

**Comment by qVortex** [comment]
thank you
