### ISSUE TITLE
Skills does not display properly DPS

### ISSUE THREAD

**Issue by 123yinlunwei** [Geigerkind/DPSMate#55]
Shadow Bolt  Drain Life    Can't pick up the data！
![qq 20170303211114](https://cloud.githubusercontent.com/assets/24893571/23552385/873d0254-0056-11e7-98da-b38992c85d66.png)

**Comment by 123yinlunwei** [comment]
![qq 20170303213713](https://cloud.githubusercontent.com/assets/24893571/23553015/a30d1908-0059-11e7-86c5-da66a467d9f1.png)

**Comment by Geigerkind** [comment]
Fixed. 
Apparently all school damage done/taken etc, strings are missing in the globalstrings.lua

Please test everything there. Meele and spell attacks for:
self -> self
self -> other
other -> self
other -> other

If it does not work. please provide me with an explained teststring that says what is the cause, target, ability, school etc.

cheers!

**Comment by Geigerkind** [comment]
Should have gotten all now, please test
