### ISSUE TITLE
Dispells contain Dispells by bosses (e.g. Garr)

### ISSUE THREAD

**Issue by Stogi7789** [Geigerkind/DPSMate#56]
![prio2](https://cloud.githubusercontent.com/assets/26174028/23569120/076a31c0-005e-11e7-9e57-b2d5ce1d09ed.PNG)

When raiding MC the dispell counter includes impossible dispells like curses (by a priest) and dispells which were done by Garr.

No error messege - for reproduction raid MC or check any tracked MC raid`s dispells.

**Comment by devilyer** [comment]
/DPSMate_!zhCN/DPSMate_ParserZHCN.lua 
line 12 :        for a,b,c,f,d in strgfind(msg, "你击中(.+)造成(%d+)伤(.*)害%（(%d+)被吸收%）。") do 
should be     for a,b,c,f,d in strgfind(msg, "你击中(.+)造成(%d+)点(.*)伤害%（(%d+)被吸收%）。") do 
:D

**Comment by Geigerkind** [comment]
Should be fixed with the next build. If it still doesn't work. Make a new ticket please.
