### ISSUE TITLE
Lots of errors.

### ISSUE THREAD

**Issue by Nordrassil** [Geigerkind/DPSMate#57]
Okay, after extensive troubleshooting, I've confirmed that the newest release I downloaded completely breaks wow.

I've tried deleting WTF folder, running only dpsmate as addon etc.

This pops up upon login:

 

"INFO: [String "DPSMate_Options:OnEvent"]:2:attempt to call method 'OnEvent' (a nil value)"

If I try to use a spell, I get :

"INFO: Interface\addons\dpsmate\dpsmate_Sync.lua:1037:attempt to call method 'awaitafflicted' (a nil value)"

 

If I try to open options:

INFO: Interface\addons\dpsmate\dpsmate_options.lua: 634: attempt to index global 'dpsmatesettings' (a nil value)

 

And it stops me from logging out

**Comment by Geigerkind** [comment]
Guess it is resolved, but I also fixed the issue. I am sorry^^
