### ISSUE TITLE
some issues for zhCN cilent

### ISSUE THREAD

**Issue by devilyer** [Geigerkind/DPSMate#58]
1、DPSMate_!zhCN.lua line 12 :
                   for a,b,c,f,d in strgfind(msg, "你击中(.+)造成(%d+)伤(.*)害%（(%d+)被吸收%）。") do 
should be   for a,b,c,f,d in strgfind(msg, "你击中(.+)造成(%d+)点(.*)伤害%（(%d+)被吸收%）。") do 

2、Pet damage is always not displayed, and whether or not to check mergepets.

3、Some options have not been translated into Chinese
![image](https://cloud.githubusercontent.com/assets/25236307/23576431/efdacf38-00df-11e7-91a8-84b2b86337b5.png)

4 、When I try to click DPSMate.L["enabledisable"] ，will show the error:
![image](https://cloud.githubusercontent.com/assets/25236307/23576459/db7d7b52-00e0-11e7-89eb-913fb9f9bc68.png)

**Comment by Geigerkind** [comment]
Fixed. Please redownload to retest!
