### ISSUE TITLE
Chinese client name display problem

### ISSUE THREAD

**Issue by shishan2017** [Geigerkind/DPSMate#61]
Chinese name of the monster and player or NPC name can not be displayed on the list, such as Enemy damage done/Enemy damage taken。

![20170304215048](https://cloud.githubusercontent.com/assets/26185327/23579298/5802dde0-0125-11e7-9915-89f57d8543ee.jpg)

**Comment by Geigerkind** [comment]
When did you did a clean download the last time?

**Comment by Geigerkind** [comment]
And which mode is this :D ?

**Comment by shishan2017** [comment]
Just now, your last update

**Comment by shishan2017** [comment]
Enemy damage taken mode

**Comment by Geigerkind** [comment]
Hey, I can't reproduce it. Did you use any special ability?

**Comment by Geigerkind** [comment]
Ah, now I know. 
You are probably using a font that is not supporting mandarin.
Unfortunately only Fritzql or so supports mandarin, I am sorry
