### ISSUE TITLE
French Client issues

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#67]
From last release : 

Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1406: attempt to perform arithmetic on local `Damount' (a nil value)

Erreur : ...nterface\AddOns\DPSMate_!frFR\DPSMate_ParserFRFR.lua:477: bad argument #1 to `strfind' (string expected, got nil)

Erreur : Interface\AddOns\DPSMate\DPSMate_Sync.lua:95: attempt to concatenate field `synckey' (a nil value)

Erreur : ...nterface\AddOns\DPSMate_!frFR\DPSMate_ParserFRFR.lua:745: attempt to call method `ReplaceSwString' (a nil value)

**Comment by Geigerkind** [comment]
Thy, will fix it this evening

**Comment by Kalandras** [comment]
Good luck dude !
I'm working on a better translation of the interface btw :) Will send you the file asap

**Comment by Geigerkind** [comment]
Aight, thy!
