### ISSUE TITLE
Addon doesn't load.

### ISSUE THREAD

**Issue by kev41** [Geigerkind/DPSMate#68]
I download your latest release, remove -b95 from the foldername but it still wont show up in the addonlist.

**Comment by Geigerkind** [comment]
The installing procedure changed. You need to put the contents of the folder now into your addon folder. So everything that is in the downloaded folder.

cheers!

**Comment by kev41** [comment]
@Geigerkind 

All like 40 folders?? and other files too, the .md file, license?
Was not like this before. Thanks for your work but now way Im scrolling through 40 additional in my already long addonlist. I guess I have to use swstats or something.
