### ISSUE TITLE
chinese client issues

### ISSUE THREAD

**Issue by korolevlong** [Geigerkind/DPSMate#69]
first Thank you very much for this.
i use it yesterday,i find a issue.
it can not statistical heal for myself.

i test this parser which in DPSMate_ParserZHCN.lua-697
你的(.+)治疗了(.+)(%d+)点生命值。

你的快速治疗治疗了rox100点生命值。
a=快速治疗
b=rox10
c=0

i think this will be right
你的(.+)治疗了(.+[^0-9])(%d+)点生命值。
你的快速治疗治疗了rox100点生命值。
a=快速治疗
b=rox
c=100

thanks.

**Comment by Geigerkind** [comment]
Thank you sir!
