### ISSUE TITLE
Boss segments not saving

### ISSUE THREAD

**Issue by vashin1** [Geigerkind/DPSMate#74]
Just as title indicated, The individual segments for bosses that DPSMate used to save no longer appear in segments, At the end of the Synced BWL and MC I only had current and total listed there.

**Comment by Geigerkind** [comment]
How am I doing that :/

**Comment by vashin1** [comment]
No idea, my "Data segments to keep" slider is in the default position of 8, and "Only keep boss fights" is checked off

**Comment by Geigerkind** [comment]
Can't really reproduce it :/
http://i.imgur.com/TKSWpVm.png

**Comment by vashin1** [comment]
I unchecked "Only keep boss fights" and this is now what I get http://imgur.com/a/q1LJJ  - I've tried on my own config and a brand new freshly wiped one as shown in my screenshot
