### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Predatorie** [Geigerkind/DPSMate#77]
Clean install today, on start up I get this error/ Let me know if there is anything else you need to know. 

![dpsmate](https://cloud.githubusercontent.com/assets/2666052/23880501/56b33c94-082a-11e7-9024-f98f47db89bd.png)

**Comment by Predatorie** [comment]
Looks like an else was used in place of an end

**Comment by Geigerkind** [comment]
U are using the development build^^
