### ISSUE TITLE
Conflict with WiM Version: 1.3.1

### ISSUE THREAD

**Issue by Predatorie** [Geigerkind/DPSMate#80]
Thanks for enlightening me earlier in regards to the dev build versus the release build and I have since reverted to a clean install of the current b100 release. 

 I don't think WiM (Warcraft instant messenger) is currently under development but with DPSMate enabled it breaks WiM. Currently using Version: 1.3.1 of WiM. I did try disabling each DPSMate module but that had no effect so I assume its something in the core add-on that is not playing well with WiM and how it parses incoming messages. Anyway just an FYI.

**Comment by Geigerkind** [comment]
ok, will look what is causing the issue

**Comment by Geigerkind** [comment]
Fixed, this was an important fix overall, thanks!
