### ISSUE TITLE
Devour Magic - parser error

### ISSUE THREAD

**Issue by kakysha** [Geigerkind/DPSMate#81]
DPSMate_Parser:752 attempt to call field ? (a nil value) on devour magic cast (both friendly and hostile targets)

Line 4 must be commented out 
`DPSMate.Parser:RegisterEvent("CHAT_MSG_SPELL_PET_BUFF")`
as you didn't provide event handler for this event, and it cause that error.

**Comment by Geigerkind** [comment]
Fixed
