### ISSUE TITLE
cn parser resist spell 

### ISSUE THREAD

**Issue by korolevlong** [Geigerkind/DPSMate#84]
the resist spell is not work，i can not fix it，can you see it? 
thanks

**Comment by Geigerkind** [comment]
SELF => Other ? or
OTher => Other ? or 
Other => Self ? or
Self => sellf ?

**Comment by korolevlong** [comment]
self spell and other spell resist ,in detail always show 0 resist . 
i see the parser is ok. i guess maybe something wrong in databuilder?

**Comment by Geigerkind** [comment]
http://i.imgur.com/WGlGbat.png

Can't see the issue, any particular spell you thought of?

**Comment by korolevlong** [comment]
[http://p1.bpimg.com/519918/86fde5826b9c2864.jpg](url)

this my combat. i dont know why.Can you give me some advice to find reason

**Comment by Geigerkind** [comment]
Are you sure that you did resist with the spell though?

**Comment by korolevlong** [comment]
yes,i am very sure. this has 8 hit.almost resist 3-4%

**Comment by korolevlong** [comment]
in my client 1.123,if spell resist,it won't enter  ParserZHCN 93 line.
could you tell me which code publish event CHAT_MSG_SPELL_SELF_DAMAGE.thank you.

**Comment by korolevlong** [comment]
i fixed it.
in my client , spell resist event is CHAT_MSG_SPELL_DAMAGESHIELDS_ON_SELF.
i don't know the reason.thank you.
