### ISSUE TITLE
French Client Nostalgeek server

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#85]
Reopen !
New erreur when dead :
https://img.kalandras.eu/C9NSUc.png
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1336: attempt to compare number with nil

Somes spells aren't count by player :
https://img.kalandras.eu/z4gFdr.png

Like "soin DE Chléo" should be add for the "Chelo" count
Same for damages
https://img.kalandras.eu/9dt2ZM.png
(I think it is the "DE" from our server ><)

**Comment by Kalandras** [comment]
It's somes spells like 
"Prière de Soin"
"Déluge de lame"
"Heurt de bouclier"
"Drain de vie"
"Potion de soin"
"Navetille"

The "DE" in capslock screw everything :x

**Comment by Geigerkind** [comment]
Wow, will ad an routine for this nostalgeek special snowflake syntax

**Comment by Geigerkind** [comment]
Added.
