### ISSUE TITLE
Addon Error by guildmate when using "Raid leader options > Hello World!"

### ISSUE THREAD

**Issue by Sulpitz** [Geigerkind/DPSMate#87]
English WoW Client
DPSMate version: V106enUS

When i click the button Hello World! it reports all group members using DPSMate. Also the error message appears on the screen of 2 of my guildmates who have the Addon installed.
 
Error:
Interface\Addons\DPSMate\DPSMate_Sync.lua:341:Attempt to index local `arg2' (a string value)

Thanks for the great Addon btw :D

Edit:
Another guildmate reportet he got the error but with version v84deDE

**Comment by Geigerkind** [comment]
Can he also confirm this issue with the current build^^?

**Comment by Sulpitz** [comment]
We used the b106 downlaod at Releases. Is that the current build or should we try the cloned version form master branch?

**Comment by Geigerkind** [comment]
Nah, I mean your other guildmate who has v84dede.

Does he still get the error with the newer version

**Comment by Geigerkind** [comment]
Nvm me, fixed
