### ISSUE TITLE
rid-5700 top members bug

### ISSUE THREAD

**Issue by wizardjames** [Geigerkind/DPSMate#88]
Hey, can you take alook at https://legacy-logs.com/Vanilla/Guild/Darrowshire/Dominion/0 Exterminate somehow got 1500 dps ona fight that when you select it hes at no dps , maybe a corrupted upload? He was kiting dragons during razorgore, hmm maybe the buffed hunters 1400% ..hmm  

Cheers

**Comment by Geigerkind** [comment]
Hmm, I probably put the decimal point at the wrong place :/

**Comment by Geigerkind** [comment]
Removed this record
