### ISSUE TITLE
Healing Stream Totem no statistic

### ISSUE THREAD

**Issue by 0ldi** [Geigerkind/DPSMate#89]
There is no heal of Healing Stream Totem in DPSMate and LL.
I know that in the combat log there is no binding of the recovered hp from a particular totem to a particular shaman. But is it possible to bind through the shaman's belonging to a particular group?
Something like:
if party member gain hp from Healing Stream Totem, check name of shaman in this group... 

p.s. [we have a problems with LL, but 3 days no answer](https://github.com/Geigerkind/Legacy-Logs-Bugtracker/issues/78), maybe i report in wrong place?

**Comment by Geigerkind** [comment]
Sorry, I was pretty busy with an surprise for you guys.
This is an DPSMate issue. Will look into it.

**Comment by Geigerkind** [comment]
Won't work every time now but it should be able to associate it to some shaman now. (Will be incorrect if more than one shaman is in a grp)
