### ISSUE TITLE
Damage sometimes gets doubled:

### ISSUE THREAD

**Issue by Geigerkind** [Geigerkind/DPSMate#9]
http://i.imgur.com/iye4Iye.png
Any idea why this happens? So far I've only seen it happen with hunters.

**Comment by Geigerkind** [comment]
Unknown cause

**Comment by Geigerkind** [comment]
I think it gets doubled if the hunter and the pet he is using have identical names. 

@From linx

**Comment by theExile015** [comment]
Yes, the problem is actual only for hunters have pets with same name. 
Anri, K1

**Comment by Geigerkind** [comment]
Will be fixed in the next version
