### ISSUE TITLE
DPSMate not showing any stats

### ISSUE THREAD

**Issue by blabsalot** [Geigerkind/DPSMate#90]
Upon login I receive [this](https://i.imgur.com/y7wOhCv.png) error and dpsmate shows nothing bar the total amount of damage done as shown [here](https://i.imgur.com/Sfp3jpd.png).

**Comment by Geigerkind** [comment]
Hey!
I can't reproduce this bug. Can you upload your interface here?

**Comment by blabsalot** [comment]
By my interface I assume you mean my wtf folder? If so, it's included below. 

[WTF.zip](https://github.com/Geigerkind/DPSMate/files/870295/WTF.zip)

**Comment by johanssonhenrik** [comment]
Same error for me. I get [this](https://imgur.com/a/Pi6uV) upon login and whenever I try to configure anything in the menu, I get [this](https://imgur.com/a/uYNd1). The DPSMate gui just displays a grey color. [greygui](https://imgur.com/a/SZtbE)

**Comment by Geigerkind** [comment]
No, I mean your interface folder

**Comment by blabsalot** [comment]
I am an idiot. 

[Here is the interface](
https://mega.nz/#!J2JWkTba!rg8_YtITtJS9KqdihvrypgL2LBr-PRWXbbElcW4K1tc
), it was too large to upload to github.

**Comment by Geigerkind** [comment]
Thank you!

**Comment by Geigerkind** [comment]
Receiving no error whatsoever. I suggest to remove DPSMate.lua and DPSMate.lua.bak from both your char and account savedVariables.
