### ISSUE TITLE
Memory footprint

### ISSUE THREAD

**Issue by shishan2017** [Geigerkind/DPSMate#91]
I found that the installation of this plug-in will change in some of the fighting is very Caton, such as AOE or Vaelastrasz the Corrupt battle, but my computer hardware, it is impossible to this situation.

**Comment by shishan2017** [comment]
We have a lot of members of the Association have also appeared in this situation

**Comment by shishan2017** [comment]
Once deleted the DPSMate, the problem is solved, this may be plug-in memory problems?

**Comment by Geigerkind** [comment]
Hey!
This problem appears on Elysium a lot. 
I suggest to set the addon memory to 200 and disable synchronization

**Comment by Geigerkind** [comment]
Anyways, it will be fixed with the next huge update
