### ISSUE TITLE
Lua Error in combat

### ISSUE THREAD

**Issue by dagochen** [Geigerkind/DPSMate#93]
![wowscrnshot_032817_174549](https://cloud.githubusercontent.com/assets/5236186/24414340/72fed150-13de-11e7-8256-cda19f107b09.jpg)

Happens randomly, did not see any pattern of occurance

**Comment by Geigerkind** [comment]
Magst mir mal nen screenshot vom combatlog machen zum gleichen Zeitpunkt, wie diese Errormeldung.
Interessiert bin ich an dein Heil events.

**Comment by dagochen** [comment]
also ich hab grad nen bwl raid gemacht, ohne dpsmate und ich hatte 0 lags, sonst ist es kaum spielbar...
vllt ruckelts auch wegen diesen errors. aber da ich ausschließlich am raiden bin ist es halt schwer zu sagen wann und wo und wie das problem auftritt. combatlog rattert halt so fix durch....da schnell genug zu reagiern wird wohl nix...
