### ISSUE TITLE
French client (Nostalgeek)

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#94]
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1338: attempt to compare number with nil

**Comment by Kalandras** [comment]
--------------------------------------------------
Nombre : Infini
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1338: attempt to compare number with nil
--------------------------------------------------
Nombre : Infini
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1335: table index is nil
--------------------------------------------------
Nombre : 2
Erreur : ...nterface\AddOns\DPSMate_!frFR\DPSMate_ParserFRFR.lua:610: invalid pattern capture

**Comment by Geigerkind** [comment]
Fixed
