### ISSUE TITLE
DPSMate.lua202:attempt to index field 'content border color'  (a nil value)

### ISSUE THREAD

**Issue by aravir009** [Geigerkind/DPSMate#96]
When installing the addon, i get this issue every time..i placed the many files in the addon folder, enabled all, and this issue comes up..i see no info in the dpsmate box..it just shows as a yellow bar only ..what is the problem?

**Comment by Geigerkind** [comment]
If you had an previous version installed, try to remove the DPSMate.lua and DPSMate.lua.bak forom your Account/SavedVariables and Account/Server/Character/SavedVariables
