### ISSUE TITLE
French Client LUA Error :

### ISSUE THREAD

**Issue by Kalandras** [Geigerkind/DPSMate#97]
Nombre : Infini
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1338: attempt to compare number with nil
--------------------------------------------------
Nombre : 1
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1335: table index is nil

**Comment by Geigerkind** [comment]
Can you tell me when it occours, with which combat message?

**Comment by Kalandras** [comment]
Almost every combat , there is infinite lua error ^^

**Comment by Geigerkind** [comment]
I can't reproduce it, so please try to pin it down.

**Comment by Kalandras** [comment]
Erreur : Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:1338: attempt to compare number with nil

https://img.kalandras.eu/QEidZt.png

When the combat begon ^^

**Comment by Geigerkind** [comment]
Fixed, thy
