### ISSUE TITLE
Why cant i find myself on the damage list?

### ISSUE THREAD

**Issue by LakeshireW** [Geigerkind/DPSMate#99]
It works for my priest character except my hunter,i just cant find my hunters dps on the list. 
 i tried to disable all my addons except DpsMate and delete all DpsMate files from Savedvariables folder,it worked ,but the issue happened again after a while.
new clue: While i check "Merge Pets " option,the issue happens ,if i dont check this option,I can find myself on the list but all my damage are merged into pet damage.I think this happens because My pet and hunter,they use the same name.

**Comment by Geigerkind** [comment]
`I think this happens because My pet and hunter,they use the same name.`

Even if this is a bug, please stop calling your pet like the hunter, how do you think should any addon differentiate you and the pet?
